# Generated from generators/ir by generators/ir_to_python.py.
# Do not edit by hand; run `npm run facades:write`.
from __future__ import annotations

FACADE_CONTRACT = {'capabilities': {'bridgeKind': 'generated',
                  'bridgeVersion': '0.1.0',
                  'features': [],
                  'host': 'photoshop',
                  'methods': {'action': ['batchPlay'],
                              'app': ['getVersion', 'getDocuments'],
                              'channel': ['getChannels',
                                          'getActiveChannels',
                                          'getComponentChannels',
                                          'getByName',
                                          'add',
                                          'remove'],
                              'document': ['getActive', 'getById', 'getLayers', 'getActiveLayers', 'saveAs', 'export'],
                              'export': ['getPresets', 'exportWithPreset'],
                              'filter': ['apply',
                                         'applyGaussianBlur',
                                         'applyHighPass',
                                         'applySharpen',
                                         'applySmartBlur'],
                              'layer': ['getActive', 'getChildren'],
                              'raw': ['evalJs', 'getPath', 'callPath'],
                              'selection': ['get',
                                            'selectAll',
                                            'deselect',
                                            'inverse',
                                            'selectRectangle',
                                            'selectEllipse',
                                            'selectPolygon',
                                            'selectRow',
                                            'selectColumn',
                                            'expand',
                                            'contract',
                                            'feather',
                                            'smooth',
                                            'grow',
                                            'translateBoundary',
                                            'save'],
                              'smartObject': ['convertToSmartObject',
                                              'newSmartObjectViaCopy',
                                              'editContents',
                                              'replaceContents'],
                              'text': ['getActive',
                                       'getByLayerId',
                                       'setContents',
                                       'setCharacterStyle',
                                       'setParagraphStyle',
                                       'setTextClickPoint',
                                       'setOrientation',
                                       'resetCharacterStyle',
                                       'convertToParagraphText',
                                       'convertToPointText',
                                       'convertToShape',
                                       'createWorkPath']},
                  'namespaces': ['app',
                                 'document',
                                 'layer',
                                 'selection',
                                 'channel',
                                 'text',
                                 'filter',
                                 'smartObject',
                                 'export',
                                 'action',
                                 'raw']},
 'classes': {'ChannelProxy': {'methods': {'remove': {'canonical': 'remove', 'returns': 'ChannelProxy'}},
                              'properties': {'id': {'canonical': 'id', 'type': 'int | str | None'},
                                             'kind': {'canonical': 'kind', 'type': 'str | None'},
                                             'name': {'canonical': 'name', 'type': 'str | None'},
                                             'opacity': {'canonical': 'opacity', 'type': 'Any'},
                                             'typename': {'canonical': 'typename', 'type': 'str | None'},
                                             'visible': {'canonical': 'visible', 'type': 'bool | None'}}},
             'CharacterStyleProxy': {'methods': {'reset': {'canonical': 'reset', 'returns': 'TextItemProxy'},
                                                 'update': {'canonical': 'update', 'returns': 'TextItemProxy'}},
                                     'properties': {}},
             'DocumentExportProxy': {'methods': {'jpg_high': {'canonical': 'jpg_high', 'returns': 'Any'},
                                                 'jpg_medium': {'canonical': 'jpg_medium', 'returns': 'Any'},
                                                 'png': {'canonical': 'png', 'returns': 'Any'},
                                                 'png_small': {'canonical': 'png_small', 'returns': 'Any'},
                                                 'psd_copy': {'canonical': 'psd_copy', 'returns': 'Any'},
                                                 'withPreset': {'canonical': 'withPreset', 'returns': 'Any'},
                                                 'with_preset': {'canonical': 'withPreset', 'returns': 'Any'}},
                                     'properties': {'presets': {'canonical': 'presets', 'type': 'list[ExportPreset]'}}},
             'DocumentProxy': {'methods': {'export': {'canonical': 'export', 'returns': 'Any'},
                                           'exportWithPreset': {'canonical': 'exportWithPreset', 'returns': 'Any'},
                                           'export_with_preset': {'canonical': 'exportWithPreset', 'returns': 'Any'},
                                           'getChannel': {'canonical': 'getChannel', 'returns': 'ChannelProxy | None'},
                                           'get_channel': {'canonical': 'getChannel', 'returns': 'ChannelProxy | None'},
                                           'refresh': {'canonical': 'refresh', 'returns': 'DocumentProxy'},
                                           'saveAs': {'canonical': 'saveAs', 'returns': 'Any'},
                                           'save_as': {'canonical': 'saveAs', 'returns': 'Any'}},
                               'properties': {'activeChannels': {'canonical': 'active_channels',
                                                                 'type': 'list[ChannelProxy]'},
                                              'activeLayers': {'canonical': 'active_layers',
                                                               'type': 'list[LayerProxy]'},
                                              'active_channels': {'canonical': 'active_channels',
                                                                  'type': 'list[ChannelProxy]'},
                                              'active_layers': {'canonical': 'active_layers',
                                                                'type': 'list[LayerProxy]'},
                                              'channels': {'canonical': 'channels', 'type': 'list[ChannelProxy]'},
                                              'componentChannels': {'canonical': 'component_channels',
                                                                    'type': 'list[ChannelProxy]'},
                                              'component_channels': {'canonical': 'component_channels',
                                                                     'type': 'list[ChannelProxy]'},
                                              'dom': {'canonical': 'dom', 'type': 'PhotoshopDomProxy'},
                                              'exports': {'canonical': 'exports', 'type': 'DocumentExportProxy'},
                                              'height': {'canonical': 'height', 'type': 'Any'},
                                              'id': {'canonical': 'id', 'type': 'int | str | None'},
                                              'layers': {'canonical': 'layers', 'type': 'list[LayerProxy]'},
                                              'mode': {'canonical': 'mode', 'type': 'str | None'},
                                              'name': {'canonical': 'name', 'type': 'str | None'},
                                              'path': {'canonical': 'path', 'type': 'str | None'},
                                              'resolution': {'canonical': 'resolution', 'type': 'Any'},
                                              'saved': {'canonical': 'saved', 'type': 'bool | None'},
                                              'selection': {'canonical': 'selection', 'type': 'SelectionProxy'},
                                              'typename': {'canonical': 'typename', 'type': 'str | None'},
                                              'width': {'canonical': 'width', 'type': 'Any'}}},
             'ExportPreset': {'methods': {},
                              'properties': {'asCopy': {'canonical': 'as_copy', 'type': 'bool'},
                                             'as_copy': {'canonical': 'as_copy', 'type': 'bool'},
                                             'description': {'canonical': 'description', 'type': 'str | None'},
                                             'format': {'canonical': 'format', 'type': 'str'},
                                             'name': {'canonical': 'name', 'type': 'str'},
                                             'options': {'canonical': 'options', 'type': 'dict[str, Any]'}}},
             'LayerFilterProxy': {'methods': {'apply': {'canonical': 'apply', 'returns': 'LayerProxy'},
                                              'applyGaussianBlur': {'canonical': 'applyGaussianBlur',
                                                                    'returns': 'LayerProxy'},
                                              'applyHighPass': {'canonical': 'applyHighPass', 'returns': 'LayerProxy'},
                                              'applySharpen': {'canonical': 'applySharpen', 'returns': 'LayerProxy'},
                                              'applySmartBlur': {'canonical': 'applySmartBlur',
                                                                 'returns': 'LayerProxy'},
                                              'apply_gaussian_blur': {'canonical': 'applyGaussianBlur',
                                                                      'returns': 'LayerProxy'},
                                              'apply_high_pass': {'canonical': 'applyHighPass',
                                                                  'returns': 'LayerProxy'},
                                              'apply_sharpen': {'canonical': 'applySharpen', 'returns': 'LayerProxy'},
                                              'apply_smart_blur': {'canonical': 'applySmartBlur',
                                                                   'returns': 'LayerProxy'}},
                                  'properties': {}},
             'LayerProxy': {'methods': {'hide': {'canonical': 'hide', 'returns': 'Any'}},
                            'properties': {'filters': {'canonical': 'filters', 'type': 'LayerFilterProxy'},
                                           'hasChildren': {'canonical': 'has_children', 'type': 'bool'},
                                           'has_children': {'canonical': 'has_children', 'type': 'bool'},
                                           'id': {'canonical': 'id', 'type': 'int | str | None'},
                                           'isSmartObject': {'canonical': 'is_smart_object', 'type': 'bool'},
                                           'is_smart_object': {'canonical': 'is_smart_object', 'type': 'bool'},
                                           'kind': {'canonical': 'kind', 'type': 'str | None'},
                                           'layers': {'canonical': 'layers', 'type': 'list[LayerProxy]'},
                                           'name': {'canonical': 'name', 'type': 'str | None'},
                                           'opacity': {'canonical': 'opacity', 'type': 'Any'},
                                           'smartObject': {'canonical': 'smart_object', 'type': 'SmartObjectProxy'},
                                           'smart_object': {'canonical': 'smart_object', 'type': 'SmartObjectProxy'},
                                           'textItem': {'canonical': 'text_item', 'type': 'TextItemProxy | None'},
                                           'text_item': {'canonical': 'text_item', 'type': 'TextItemProxy | None'},
                                           'typename': {'canonical': 'typename', 'type': 'str | None'},
                                           'visible': {'canonical': 'visible', 'type': 'bool | None'}}},
             'ParagraphStyleProxy': {'methods': {'update': {'canonical': 'update', 'returns': 'TextItemProxy'}},
                                     'properties': {}},
             'Photoshop': {'methods': {'batchPlay': {'canonical': 'batchPlay',
                                                     'mutatesState': True,
                                                     'raw': False,
                                                     'requiresModalWhenMutating': True,
                                                     'returns': 'Any',
                                                     'source': 'action.batchPlay'},
                                       'batch_play': {'canonical': 'batchPlay',
                                                      'mutatesState': True,
                                                      'raw': False,
                                                      'requiresModalWhenMutating': True,
                                                      'returns': 'Any',
                                                      'source': 'action.batchPlay'}},
                           'properties': {'activeDocument': {'canonical': 'active_document',
                                                             'mutatesState': False,
                                                             'raw': False,
                                                             'requiresModalWhenMutating': False,
                                                             'source': 'document.getActive',
                                                             'type': 'DocumentProxy | None'},
                                          'activeLayer': {'canonical': 'active_layer',
                                                          'mutatesState': False,
                                                          'raw': False,
                                                          'requiresModalWhenMutating': False,
                                                          'source': 'layer.getActive',
                                                          'type': 'LayerProxy | None'},
                                          'activeLayers': {'canonical': 'active_layers',
                                                           'mutatesState': False,
                                                           'raw': False,
                                                           'requiresModalWhenMutating': False,
                                                           'source': 'document.getActiveLayers',
                                                           'type': 'list[LayerProxy]'},
                                          'activeText': {'canonical': 'active_text',
                                                         'mutatesState': False,
                                                         'raw': False,
                                                         'requiresModalWhenMutating': False,
                                                         'source': 'text.getActive',
                                                         'type': 'TextItemProxy | None'},
                                          'active_document': {'canonical': 'active_document',
                                                              'mutatesState': False,
                                                              'raw': False,
                                                              'requiresModalWhenMutating': False,
                                                              'source': 'document.getActive',
                                                              'type': 'DocumentProxy | None'},
                                          'active_layer': {'canonical': 'active_layer',
                                                           'mutatesState': False,
                                                           'raw': False,
                                                           'requiresModalWhenMutating': False,
                                                           'source': 'layer.getActive',
                                                           'type': 'LayerProxy | None'},
                                          'active_layers': {'canonical': 'active_layers',
                                                            'mutatesState': False,
                                                            'raw': False,
                                                            'requiresModalWhenMutating': False,
                                                            'source': 'document.getActiveLayers',
                                                            'type': 'list[LayerProxy]'},
                                          'active_text': {'canonical': 'active_text',
                                                          'mutatesState': False,
                                                          'raw': False,
                                                          'requiresModalWhenMutating': False,
                                                          'source': 'text.getActive',
                                                          'type': 'TextItemProxy | None'},
                                          'channels': {'canonical': 'channels',
                                                       'mutatesState': False,
                                                       'raw': False,
                                                       'requiresModalWhenMutating': False,
                                                       'source': 'channel.getChannels',
                                                       'type': 'list[ChannelProxy]'},
                                          'documents': {'canonical': 'documents',
                                                        'mutatesState': False,
                                                        'raw': False,
                                                        'requiresModalWhenMutating': False,
                                                        'source': 'app.getDocuments',
                                                        'type': 'list[DocumentProxy]'},
                                          'exportPresets': {'canonical': 'export_presets',
                                                            'mutatesState': False,
                                                            'raw': False,
                                                            'requiresModalWhenMutating': False,
                                                            'source': 'export.getPresets',
                                                            'type': 'list[ExportPreset]'},
                                          'export_presets': {'canonical': 'export_presets',
                                                             'mutatesState': False,
                                                             'raw': False,
                                                             'requiresModalWhenMutating': False,
                                                             'source': 'export.getPresets',
                                                             'type': 'list[ExportPreset]'},
                                          'selection': {'canonical': 'selection',
                                                        'mutatesState': False,
                                                        'raw': False,
                                                        'requiresModalWhenMutating': False,
                                                        'source': 'selection.get',
                                                        'type': 'SelectionProxy | None'},
                                          'version': {'canonical': 'version',
                                                      'mutatesState': False,
                                                      'raw': False,
                                                      'requiresModalWhenMutating': False,
                                                      'source': 'app.getVersion',
                                                      'type': 'str'}}},
             'PhotoshopAction': {'methods': {'batchPlay': {'canonical': 'batchPlay',
                                                           'mutatesState': True,
                                                           'raw': False,
                                                           'requiresModalWhenMutating': True,
                                                           'returns': 'Any',
                                                           'source': 'action.batchPlay'},
                                             'batch_play': {'canonical': 'batchPlay',
                                                            'mutatesState': True,
                                                            'raw': False,
                                                            'requiresModalWhenMutating': True,
                                                            'returns': 'Any',
                                                            'source': 'action.batchPlay'}},
                                 'properties': {}},
             'PhotoshopApp': {'methods': {},
                              'properties': {'activeDocument': {'canonical': 'active_document',
                                                                'mutatesState': False,
                                                                'raw': False,
                                                                'requiresModalWhenMutating': False,
                                                                'source': 'document.getActive',
                                                                'type': 'DocumentProxy | None'},
                                             'activeLayer': {'canonical': 'active_layer',
                                                             'mutatesState': False,
                                                             'raw': False,
                                                             'requiresModalWhenMutating': False,
                                                             'source': 'layer.getActive',
                                                             'type': 'LayerProxy | None'},
                                             'activeLayers': {'canonical': 'active_layers',
                                                              'mutatesState': False,
                                                              'raw': False,
                                                              'requiresModalWhenMutating': False,
                                                              'source': 'document.getActiveLayers',
                                                              'type': 'list[LayerProxy]'},
                                             'activeText': {'canonical': 'active_text',
                                                            'mutatesState': False,
                                                            'raw': False,
                                                            'requiresModalWhenMutating': False,
                                                            'source': 'text.getActive',
                                                            'type': 'TextItemProxy | None'},
                                             'active_document': {'canonical': 'active_document',
                                                                 'mutatesState': False,
                                                                 'raw': False,
                                                                 'requiresModalWhenMutating': False,
                                                                 'source': 'document.getActive',
                                                                 'type': 'DocumentProxy | None'},
                                             'active_layer': {'canonical': 'active_layer',
                                                              'mutatesState': False,
                                                              'raw': False,
                                                              'requiresModalWhenMutating': False,
                                                              'source': 'layer.getActive',
                                                              'type': 'LayerProxy | None'},
                                             'active_layers': {'canonical': 'active_layers',
                                                               'mutatesState': False,
                                                               'raw': False,
                                                               'requiresModalWhenMutating': False,
                                                               'source': 'document.getActiveLayers',
                                                               'type': 'list[LayerProxy]'},
                                             'active_text': {'canonical': 'active_text',
                                                             'mutatesState': False,
                                                             'raw': False,
                                                             'requiresModalWhenMutating': False,
                                                             'source': 'text.getActive',
                                                             'type': 'TextItemProxy | None'},
                                             'channels': {'canonical': 'channels',
                                                          'mutatesState': False,
                                                          'raw': False,
                                                          'requiresModalWhenMutating': False,
                                                          'source': 'channel.getChannels',
                                                          'type': 'list[ChannelProxy]'},
                                             'documents': {'canonical': 'documents',
                                                           'mutatesState': False,
                                                           'raw': False,
                                                           'requiresModalWhenMutating': False,
                                                           'source': 'app.getDocuments',
                                                           'type': 'list[DocumentProxy]'},
                                             'exportPresets': {'canonical': 'export_presets',
                                                               'mutatesState': False,
                                                               'raw': False,
                                                               'requiresModalWhenMutating': False,
                                                               'source': 'export.getPresets',
                                                               'type': 'list[ExportPreset]'},
                                             'export_presets': {'canonical': 'export_presets',
                                                                'mutatesState': False,
                                                                'raw': False,
                                                                'requiresModalWhenMutating': False,
                                                                'source': 'export.getPresets',
                                                                'type': 'list[ExportPreset]'},
                                             'selection': {'canonical': 'selection',
                                                           'mutatesState': False,
                                                           'raw': False,
                                                           'requiresModalWhenMutating': False,
                                                           'source': 'selection.get',
                                                           'type': 'SelectionProxy | None'},
                                             'version': {'canonical': 'version',
                                                         'mutatesState': False,
                                                         'raw': False,
                                                         'requiresModalWhenMutating': False,
                                                         'source': 'app.getVersion',
                                                         'type': 'str'}}},
             'PhotoshopDomProxy': {'methods': {'call': {'canonical': 'call', 'returns': 'Any'},
                                               'get': {'canonical': 'get', 'returns': 'Any'}},
                                   'properties': {}},
             'SelectionProxy': {'methods': {'contract': {'canonical': 'contract', 'returns': 'SelectionProxy'},
                                            'deselect': {'canonical': 'deselect', 'returns': 'SelectionProxy'},
                                            'expand': {'canonical': 'expand', 'returns': 'SelectionProxy'},
                                            'feather': {'canonical': 'feather', 'returns': 'SelectionProxy'},
                                            'grow': {'canonical': 'grow', 'returns': 'SelectionProxy'},
                                            'inverse': {'canonical': 'inverse', 'returns': 'SelectionProxy'},
                                            'refresh': {'canonical': 'refresh', 'returns': 'SelectionProxy'},
                                            'save': {'canonical': 'save', 'returns': 'SelectionProxy'},
                                            'selectAll': {'canonical': 'selectAll', 'returns': 'SelectionProxy'},
                                            'selectColumn': {'canonical': 'selectColumn', 'returns': 'SelectionProxy'},
                                            'selectEllipse': {'canonical': 'selectEllipse',
                                                              'returns': 'SelectionProxy'},
                                            'selectPolygon': {'canonical': 'selectPolygon',
                                                              'returns': 'SelectionProxy'},
                                            'selectRectangle': {'canonical': 'selectRectangle',
                                                                'returns': 'SelectionProxy'},
                                            'selectRow': {'canonical': 'selectRow', 'returns': 'SelectionProxy'},
                                            'select_all': {'canonical': 'selectAll', 'returns': 'SelectionProxy'},
                                            'select_column': {'canonical': 'selectColumn', 'returns': 'SelectionProxy'},
                                            'select_ellipse': {'canonical': 'selectEllipse',
                                                               'returns': 'SelectionProxy'},
                                            'select_polygon': {'canonical': 'selectPolygon',
                                                               'returns': 'SelectionProxy'},
                                            'select_rectangle': {'canonical': 'selectRectangle',
                                                                 'returns': 'SelectionProxy'},
                                            'select_row': {'canonical': 'selectRow', 'returns': 'SelectionProxy'},
                                            'smooth': {'canonical': 'smooth', 'returns': 'SelectionProxy'},
                                            'translateBoundary': {'canonical': 'translateBoundary',
                                                                  'returns': 'SelectionProxy'},
                                            'translate_boundary': {'canonical': 'translateBoundary',
                                                                   'returns': 'SelectionProxy'}},
                                'properties': {'bounds': {'canonical': 'bounds', 'type': 'dict[str, Any] | None'},
                                               'docId': {'canonical': 'doc_id', 'type': 'int | str | None'},
                                               'doc_id': {'canonical': 'doc_id', 'type': 'int | str | None'},
                                               'solid': {'canonical': 'solid', 'type': 'bool | None'},
                                               'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'SmartObjectProxy': {'methods': {'convertToSmartObject': {'canonical': 'convertToSmartObject',
                                                                       'returns': 'LayerProxy'},
                                              'convert_to_smart_object': {'canonical': 'convertToSmartObject',
                                                                          'returns': 'LayerProxy'},
                                              'editContents': {'canonical': 'editContents', 'returns': 'LayerProxy'},
                                              'edit_contents': {'canonical': 'editContents', 'returns': 'LayerProxy'},
                                              'newSmartObjectViaCopy': {'canonical': 'newSmartObjectViaCopy',
                                                                        'returns': 'LayerProxy'},
                                              'new_smart_object_via_copy': {'canonical': 'newSmartObjectViaCopy',
                                                                            'returns': 'LayerProxy'},
                                              'replaceContents': {'canonical': 'replaceContents',
                                                                  'returns': 'LayerProxy'},
                                              'replace_contents': {'canonical': 'replaceContents',
                                                                   'returns': 'LayerProxy'}},
                                  'properties': {}},
             'TextItemProxy': {'methods': {'convertToParagraphText': {'canonical': 'convertToParagraphText',
                                                                      'returns': 'TextItemProxy'},
                                           'convertToPointText': {'canonical': 'convertToPointText',
                                                                  'returns': 'TextItemProxy'},
                                           'convertToShape': {'canonical': 'convertToShape',
                                                              'returns': 'TextItemProxy'},
                                           'convert_to_paragraph_text': {'canonical': 'convertToParagraphText',
                                                                         'returns': 'TextItemProxy'},
                                           'convert_to_point_text': {'canonical': 'convertToPointText',
                                                                     'returns': 'TextItemProxy'},
                                           'convert_to_shape': {'canonical': 'convertToShape',
                                                                'returns': 'TextItemProxy'},
                                           'createWorkPath': {'canonical': 'createWorkPath',
                                                              'returns': 'TextItemProxy'},
                                           'create_work_path': {'canonical': 'createWorkPath',
                                                                'returns': 'TextItemProxy'},
                                           'refresh': {'canonical': 'refresh', 'returns': 'TextItemProxy'},
                                           'setCharacterStyle': {'canonical': 'setCharacterStyle',
                                                                 'returns': 'TextItemProxy'},
                                           'setContents': {'canonical': 'setContents', 'returns': 'TextItemProxy'},
                                           'setOrientation': {'canonical': 'setOrientation',
                                                              'returns': 'TextItemProxy'},
                                           'setParagraphStyle': {'canonical': 'setParagraphStyle',
                                                                 'returns': 'TextItemProxy'},
                                           'setTextClickPoint': {'canonical': 'setTextClickPoint',
                                                                 'returns': 'TextItemProxy'},
                                           'set_character_style': {'canonical': 'setCharacterStyle',
                                                                   'returns': 'TextItemProxy'},
                                           'set_contents': {'canonical': 'setContents', 'returns': 'TextItemProxy'},
                                           'set_orientation': {'canonical': 'setOrientation',
                                                               'returns': 'TextItemProxy'},
                                           'set_paragraph_style': {'canonical': 'setParagraphStyle',
                                                                   'returns': 'TextItemProxy'},
                                           'set_text_click_point': {'canonical': 'setTextClickPoint',
                                                                    'returns': 'TextItemProxy'}},
                               'properties': {'characterStyle': {'canonical': 'character_style',
                                                                 'type': 'CharacterStyleProxy'},
                                              'character_style': {'canonical': 'character_style',
                                                                  'type': 'CharacterStyleProxy'},
                                              'contents': {'canonical': 'contents', 'type': 'str | None'},
                                              'isParagraphText': {'canonical': 'is_paragraph_text',
                                                                  'type': 'bool | None'},
                                              'isPointText': {'canonical': 'is_point_text', 'type': 'bool | None'},
                                              'is_paragraph_text': {'canonical': 'is_paragraph_text',
                                                                    'type': 'bool | None'},
                                              'is_point_text': {'canonical': 'is_point_text', 'type': 'bool | None'},
                                              'layerId': {'canonical': 'layer_id', 'type': 'int | str | None'},
                                              'layer_id': {'canonical': 'layer_id', 'type': 'int | str | None'},
                                              'orientation': {'canonical': 'orientation', 'type': 'str | None'},
                                              'paragraphStyle': {'canonical': 'paragraph_style',
                                                                 'type': 'ParagraphStyleProxy'},
                                              'paragraph_style': {'canonical': 'paragraph_style',
                                                                  'type': 'ParagraphStyleProxy'},
                                              'textClickPoint': {'canonical': 'text_click_point',
                                                                 'type': 'dict[str, Any] | None'},
                                              'text_click_point': {'canonical': 'text_click_point',
                                                                   'type': 'dict[str, Any] | None'},
                                              'typename': {'canonical': 'typename', 'type': 'str | None'}}}},
 'host': 'photoshop',
 'version': '0.1.0'}
