# Generated from generators/ir by generators/ir_to_python.py.
# Do not edit by hand; run `npm run facades:write`.
from __future__ import annotations

FACADE_CONTRACT = {'capabilities': {'bridgeKind': 'generated',
                  'bridgeVersion': '0.1.0',
                  'features': [],
                  'host': 'after-effects',
                  'methods': {'app': ['getVersion'],
                              'effect': ['getEffects', 'getByName'],
                              'item': ['getById', 'getByName'],
                              'layer': ['getLayers', 'getSelected', 'getById'],
                              'mask': ['getMasks'],
                              'outputModule': ['getModules',
                                               'getByIndex',
                                               'applyTemplate',
                                               'setSettings',
                                               'setOutputPath',
                                               'saveAsTemplate'],
                              'project': ['getActive',
                                          'getItems',
                                          'getCompositions',
                                          'getFootageItems',
                                          'getFolders',
                                          'getActiveItem',
                                          'getSelectedItems'],
                              'raw': ['evalExtendScript'],
                              'renderQueue': ['get',
                                              'getItems',
                                              'getItemByIndex',
                                              'addComposition',
                                              'queueSelectedCompositions',
                                              'render',
                                              'pauseRendering',
                                              'stopRendering',
                                              'showWindow',
                                              'queueInAME',
                                              'setQueueNotify'],
                              'renderQueueItem': ['applyTemplate', 'setSettings', 'setRender', 'setQueueItemNotify'],
                              'text': ['getSourceText', 'setSourceText']},
                  'namespaces': ['app',
                                 'project',
                                 'item',
                                 'layer',
                                 'mask',
                                 'effect',
                                 'text',
                                 'renderQueue',
                                 'renderQueueItem',
                                 'outputModule',
                                 'raw']},
 'classes': {'AfterEffects': {'methods': {},
                              'properties': {'activeItem': {'canonical': 'active_item',
                                                            'mutatesState': False,
                                                            'raw': False,
                                                            'requiresModalWhenMutating': False,
                                                            'source': 'project.getActiveItem',
                                                            'type': 'ProjectItemProxy | None'},
                                             'activeProject': {'canonical': 'active_project',
                                                               'mutatesState': False,
                                                               'raw': False,
                                                               'requiresModalWhenMutating': False,
                                                               'source': 'project.getActive',
                                                               'type': 'ProjectProxy | None'},
                                             'active_item': {'canonical': 'active_item',
                                                             'mutatesState': False,
                                                             'raw': False,
                                                             'requiresModalWhenMutating': False,
                                                             'source': 'project.getActiveItem',
                                                             'type': 'ProjectItemProxy | None'},
                                             'active_project': {'canonical': 'active_project',
                                                                'mutatesState': False,
                                                                'raw': False,
                                                                'requiresModalWhenMutating': False,
                                                                'source': 'project.getActive',
                                                                'type': 'ProjectProxy | None'},
                                             'selectedItems': {'canonical': 'selected_items',
                                                               'mutatesState': False,
                                                               'raw': False,
                                                               'requiresModalWhenMutating': False,
                                                               'source': 'project.getSelectedItems',
                                                               'type': 'list[ProjectItemProxy]'},
                                             'selected_items': {'canonical': 'selected_items',
                                                                'mutatesState': False,
                                                                'raw': False,
                                                                'requiresModalWhenMutating': False,
                                                                'source': 'project.getSelectedItems',
                                                                'type': 'list[ProjectItemProxy]'},
                                             'version': {'canonical': 'version',
                                                         'mutatesState': False,
                                                         'raw': False,
                                                         'requiresModalWhenMutating': False,
                                                         'source': 'app.getVersion',
                                                         'type': 'str'}}},
             'AfterEffectsApp': {'methods': {},
                                 'properties': {'activeItem': {'canonical': 'active_item',
                                                               'mutatesState': False,
                                                               'raw': False,
                                                               'requiresModalWhenMutating': False,
                                                               'source': 'project.getActiveItem',
                                                               'type': 'ProjectItemProxy | None'},
                                                'activeProject': {'canonical': 'active_project',
                                                                  'mutatesState': False,
                                                                  'raw': False,
                                                                  'requiresModalWhenMutating': False,
                                                                  'source': 'project.getActive',
                                                                  'type': 'ProjectProxy | None'},
                                                'active_item': {'canonical': 'active_item',
                                                                'mutatesState': False,
                                                                'raw': False,
                                                                'requiresModalWhenMutating': False,
                                                                'source': 'project.getActiveItem',
                                                                'type': 'ProjectItemProxy | None'},
                                                'active_project': {'canonical': 'active_project',
                                                                   'mutatesState': False,
                                                                   'raw': False,
                                                                   'requiresModalWhenMutating': False,
                                                                   'source': 'project.getActive',
                                                                   'type': 'ProjectProxy | None'},
                                                'selectedItems': {'canonical': 'selected_items',
                                                                  'mutatesState': False,
                                                                  'raw': False,
                                                                  'requiresModalWhenMutating': False,
                                                                  'source': 'project.getSelectedItems',
                                                                  'type': 'list[ProjectItemProxy]'},
                                                'selected_items': {'canonical': 'selected_items',
                                                                   'mutatesState': False,
                                                                   'raw': False,
                                                                   'requiresModalWhenMutating': False,
                                                                   'source': 'project.getSelectedItems',
                                                                   'type': 'list[ProjectItemProxy]'},
                                                'version': {'canonical': 'version',
                                                            'mutatesState': False,
                                                            'raw': False,
                                                            'requiresModalWhenMutating': False,
                                                            'source': 'app.getVersion',
                                                            'type': 'str'}}},
             'CompositionProxy': {'methods': {'addToRenderQueue': {'canonical': 'addToRenderQueue',
                                                                   'returns': 'RenderQueueItemProxy'},
                                              'add_to_render_queue': {'canonical': 'addToRenderQueue',
                                                                      'returns': 'RenderQueueItemProxy'},
                                              'getLayerById': {'canonical': 'getLayerById',
                                                               'returns': 'LayerProxy | None'},
                                              'get_layer_by_id': {'canonical': 'getLayerById',
                                                                  'returns': 'LayerProxy | None'}},
                                  'properties': {'duration': {'canonical': 'duration', 'type': 'float | None'},
                                                 'frameRate': {'canonical': 'frame_rate', 'type': 'float | None'},
                                                 'frame_rate': {'canonical': 'frame_rate', 'type': 'float | None'},
                                                 'height': {'canonical': 'height', 'type': 'int | None'},
                                                 'id': {'canonical': 'id', 'type': 'Any'},
                                                 'index': {'canonical': 'index', 'type': 'int | None'},
                                                 'isActive': {'canonical': 'is_active', 'type': 'bool | None'},
                                                 'is_active': {'canonical': 'is_active', 'type': 'bool | None'},
                                                 'itemType': {'canonical': 'item_type', 'type': 'str | None'},
                                                 'item_type': {'canonical': 'item_type', 'type': 'str | None'},
                                                 'layers': {'canonical': 'layers', 'type': 'list[LayerProxy]'},
                                                 'name': {'canonical': 'name', 'type': 'str | None'},
                                                 'numLayers': {'canonical': 'num_layers', 'type': 'int | None'},
                                                 'num_layers': {'canonical': 'num_layers', 'type': 'int | None'},
                                                 'parentFolderId': {'canonical': 'parent_folder_id', 'type': 'Any'},
                                                 'parentFolderName': {'canonical': 'parent_folder_name',
                                                                      'type': 'str | None'},
                                                 'parent_folder_id': {'canonical': 'parent_folder_id', 'type': 'Any'},
                                                 'parent_folder_name': {'canonical': 'parent_folder_name',
                                                                        'type': 'str | None'},
                                                 'selected': {'canonical': 'selected', 'type': 'bool | None'},
                                                 'selectedLayers': {'canonical': 'selected_layers',
                                                                    'type': 'list[LayerProxy]'},
                                                 'selected_layers': {'canonical': 'selected_layers',
                                                                     'type': 'list[LayerProxy]'},
                                                 'typeName': {'canonical': 'type_name', 'type': 'str | None'},
                                                 'type_name': {'canonical': 'type_name', 'type': 'str | None'},
                                                 'typename': {'canonical': 'typename', 'type': 'str | None'},
                                                 'width': {'canonical': 'width', 'type': 'int | None'},
                                                 'workAreaDuration': {'canonical': 'work_area_duration',
                                                                      'type': 'float | None'},
                                                 'workAreaStart': {'canonical': 'work_area_start',
                                                                   'type': 'float | None'},
                                                 'work_area_duration': {'canonical': 'work_area_duration',
                                                                        'type': 'float | None'},
                                                 'work_area_start': {'canonical': 'work_area_start',
                                                                     'type': 'float | None'}}},
             'EffectProxy': {'methods': {},
                             'properties': {'active': {'canonical': 'active', 'type': 'bool | None'},
                                            'enabled': {'canonical': 'enabled', 'type': 'bool | None'},
                                            'id': {'canonical': 'id', 'type': 'Any'},
                                            'index': {'canonical': 'index', 'type': 'int | None'},
                                            'matchName': {'canonical': 'match_name', 'type': 'str | None'},
                                            'match_name': {'canonical': 'match_name', 'type': 'str | None'},
                                            'name': {'canonical': 'name', 'type': 'str | None'},
                                            'propertyCount': {'canonical': 'property_count', 'type': 'int | None'},
                                            'property_count': {'canonical': 'property_count', 'type': 'int | None'},
                                            'selected': {'canonical': 'selected', 'type': 'bool | None'},
                                            'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'FolderItemProxy': {'methods': {},
                                 'properties': {'id': {'canonical': 'id', 'type': 'Any'},
                                                'index': {'canonical': 'index', 'type': 'int | None'},
                                                'isActive': {'canonical': 'is_active', 'type': 'bool | None'},
                                                'is_active': {'canonical': 'is_active', 'type': 'bool | None'},
                                                'itemCount': {'canonical': 'item_count', 'type': 'int | None'},
                                                'itemType': {'canonical': 'item_type', 'type': 'str | None'},
                                                'item_count': {'canonical': 'item_count', 'type': 'int | None'},
                                                'item_type': {'canonical': 'item_type', 'type': 'str | None'},
                                                'name': {'canonical': 'name', 'type': 'str | None'},
                                                'parentFolderId': {'canonical': 'parent_folder_id', 'type': 'Any'},
                                                'parentFolderName': {'canonical': 'parent_folder_name',
                                                                     'type': 'str | None'},
                                                'parent_folder_id': {'canonical': 'parent_folder_id', 'type': 'Any'},
                                                'parent_folder_name': {'canonical': 'parent_folder_name',
                                                                       'type': 'str | None'},
                                                'selected': {'canonical': 'selected', 'type': 'bool | None'},
                                                'typeName': {'canonical': 'type_name', 'type': 'str | None'},
                                                'type_name': {'canonical': 'type_name', 'type': 'str | None'},
                                                'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'FootageItemProxy': {'methods': {},
                                  'properties': {'duration': {'canonical': 'duration', 'type': 'float | None'},
                                                 'filePath': {'canonical': 'file_path', 'type': 'str | None'},
                                                 'file_path': {'canonical': 'file_path', 'type': 'str | None'},
                                                 'frameRate': {'canonical': 'frame_rate', 'type': 'float | None'},
                                                 'frame_rate': {'canonical': 'frame_rate', 'type': 'float | None'},
                                                 'hasAudio': {'canonical': 'has_audio', 'type': 'bool | None'},
                                                 'hasVideo': {'canonical': 'has_video', 'type': 'bool | None'},
                                                 'has_audio': {'canonical': 'has_audio', 'type': 'bool | None'},
                                                 'has_video': {'canonical': 'has_video', 'type': 'bool | None'},
                                                 'height': {'canonical': 'height', 'type': 'int | None'},
                                                 'id': {'canonical': 'id', 'type': 'Any'},
                                                 'index': {'canonical': 'index', 'type': 'int | None'},
                                                 'isActive': {'canonical': 'is_active', 'type': 'bool | None'},
                                                 'is_active': {'canonical': 'is_active', 'type': 'bool | None'},
                                                 'itemType': {'canonical': 'item_type', 'type': 'str | None'},
                                                 'item_type': {'canonical': 'item_type', 'type': 'str | None'},
                                                 'missingFootage': {'canonical': 'missing_footage',
                                                                    'type': 'bool | None'},
                                                 'missing_footage': {'canonical': 'missing_footage',
                                                                     'type': 'bool | None'},
                                                 'name': {'canonical': 'name', 'type': 'str | None'},
                                                 'parentFolderId': {'canonical': 'parent_folder_id', 'type': 'Any'},
                                                 'parentFolderName': {'canonical': 'parent_folder_name',
                                                                      'type': 'str | None'},
                                                 'parent_folder_id': {'canonical': 'parent_folder_id', 'type': 'Any'},
                                                 'parent_folder_name': {'canonical': 'parent_folder_name',
                                                                        'type': 'str | None'},
                                                 'selected': {'canonical': 'selected', 'type': 'bool | None'},
                                                 'typeName': {'canonical': 'type_name', 'type': 'str | None'},
                                                 'type_name': {'canonical': 'type_name', 'type': 'str | None'},
                                                 'typename': {'canonical': 'typename', 'type': 'str | None'},
                                                 'width': {'canonical': 'width', 'type': 'int | None'}}},
             'LayerProxy': {'methods': {'getEffect': {'canonical': 'getEffect', 'returns': 'EffectProxy | None'},
                                        'get_effect': {'canonical': 'getEffect', 'returns': 'EffectProxy | None'},
                                        'setSourceText': {'canonical': 'setSourceText', 'returns': 'SourceTextProxy'},
                                        'set_source_text': {'canonical': 'setSourceText',
                                                            'returns': 'SourceTextProxy'}},
                            'properties': {'compId': {'canonical': 'comp_id', 'type': 'Any'},
                                           'comp_id': {'canonical': 'comp_id', 'type': 'Any'},
                                           'effects': {'canonical': 'effects', 'type': 'list[EffectProxy]'},
                                           'enabled': {'canonical': 'enabled', 'type': 'bool | None'},
                                           'hasAudio': {'canonical': 'has_audio', 'type': 'bool | None'},
                                           'hasVideo': {'canonical': 'has_video', 'type': 'bool | None'},
                                           'has_audio': {'canonical': 'has_audio', 'type': 'bool | None'},
                                           'has_video': {'canonical': 'has_video', 'type': 'bool | None'},
                                           'height': {'canonical': 'height', 'type': 'int | None'},
                                           'id': {'canonical': 'id', 'type': 'Any'},
                                           'inPoint': {'canonical': 'in_point', 'type': 'float | None'},
                                           'in_point': {'canonical': 'in_point', 'type': 'float | None'},
                                           'index': {'canonical': 'index', 'type': 'int | None'},
                                           'isText': {'canonical': 'is_text', 'type': 'bool | None'},
                                           'is_text': {'canonical': 'is_text', 'type': 'bool | None'},
                                           'layerType': {'canonical': 'layer_type', 'type': 'str | None'},
                                           'layer_type': {'canonical': 'layer_type', 'type': 'str | None'},
                                           'locked': {'canonical': 'locked', 'type': 'bool | None'},
                                           'masks': {'canonical': 'masks', 'type': 'list[MaskProxy]'},
                                           'name': {'canonical': 'name', 'type': 'str | None'},
                                           'outPoint': {'canonical': 'out_point', 'type': 'float | None'},
                                           'out_point': {'canonical': 'out_point', 'type': 'float | None'},
                                           'selected': {'canonical': 'selected', 'type': 'bool | None'},
                                           'shy': {'canonical': 'shy', 'type': 'bool | None'},
                                           'solo': {'canonical': 'solo', 'type': 'bool | None'},
                                           'sourceId': {'canonical': 'source_id', 'type': 'Any'},
                                           'sourceName': {'canonical': 'source_name', 'type': 'str | None'},
                                           'sourceText': {'canonical': 'source_text', 'type': 'SourceTextProxy | None'},
                                           'source_id': {'canonical': 'source_id', 'type': 'Any'},
                                           'source_name': {'canonical': 'source_name', 'type': 'str | None'},
                                           'source_text': {'canonical': 'source_text',
                                                           'type': 'SourceTextProxy | None'},
                                           'startTime': {'canonical': 'start_time', 'type': 'float | None'},
                                           'start_time': {'canonical': 'start_time', 'type': 'float | None'},
                                           'stretch': {'canonical': 'stretch', 'type': 'float | None'},
                                           'typeName': {'canonical': 'type_name', 'type': 'str | None'},
                                           'type_name': {'canonical': 'type_name', 'type': 'str | None'},
                                           'typename': {'canonical': 'typename', 'type': 'str | None'},
                                           'width': {'canonical': 'width', 'type': 'int | None'}}},
             'MaskProxy': {'methods': {},
                           'properties': {'expansion': {'canonical': 'expansion', 'type': 'Any'},
                                          'feather': {'canonical': 'feather', 'type': 'Any'},
                                          'id': {'canonical': 'id', 'type': 'Any'},
                                          'index': {'canonical': 'index', 'type': 'int | None'},
                                          'inverted': {'canonical': 'inverted', 'type': 'bool | None'},
                                          'locked': {'canonical': 'locked', 'type': 'bool | None'},
                                          'maskMode': {'canonical': 'mask_mode', 'type': 'str | None'},
                                          'mask_mode': {'canonical': 'mask_mode', 'type': 'str | None'},
                                          'name': {'canonical': 'name', 'type': 'str | None'},
                                          'opacity': {'canonical': 'opacity', 'type': 'Any'},
                                          'rotoBezier': {'canonical': 'roto_bezier', 'type': 'bool | None'},
                                          'roto_bezier': {'canonical': 'roto_bezier', 'type': 'bool | None'},
                                          'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'OutputModuleProxy': {'methods': {'applyTemplate': {'canonical': 'applyTemplate',
                                                                 'returns': 'OutputModuleProxy'},
                                               'apply_template': {'canonical': 'applyTemplate',
                                                                  'returns': 'OutputModuleProxy'},
                                               'saveAsTemplate': {'canonical': 'saveAsTemplate',
                                                                  'returns': 'OutputModuleProxy'},
                                               'save_as_template': {'canonical': 'saveAsTemplate',
                                                                    'returns': 'OutputModuleProxy'},
                                               'setOutputPath': {'canonical': 'setOutputPath',
                                                                 'returns': 'OutputModuleProxy'},
                                               'setSettings': {'canonical': 'setSettings',
                                                               'returns': 'OutputModuleProxy'},
                                               'set_output_path': {'canonical': 'setOutputPath',
                                                                   'returns': 'OutputModuleProxy'},
                                               'set_settings': {'canonical': 'setSettings',
                                                                'returns': 'OutputModuleProxy'}},
                                   'properties': {'filePath': {'canonical': 'file_path', 'type': 'str | None'},
                                                  'file_path': {'canonical': 'file_path', 'type': 'str | None'},
                                                  'includeSourceXmp': {'canonical': 'include_source_xmp',
                                                                       'type': 'bool | None'},
                                                  'include_source_xmp': {'canonical': 'include_source_xmp',
                                                                         'type': 'bool | None'},
                                                  'index': {'canonical': 'index', 'type': 'int | None'},
                                                  'itemIndex': {'canonical': 'item_index', 'type': 'int | None'},
                                                  'item_index': {'canonical': 'item_index', 'type': 'int | None'},
                                                  'name': {'canonical': 'name', 'type': 'str | None'},
                                                  'outputPath': {'canonical': 'output_path', 'type': 'str | None'},
                                                  'output_path': {'canonical': 'output_path', 'type': 'str | None'},
                                                  'postRenderAction': {'canonical': 'post_render_action',
                                                                       'type': 'str | None'},
                                                  'post_render_action': {'canonical': 'post_render_action',
                                                                         'type': 'str | None'},
                                                  'settings': {'canonical': 'settings',
                                                               'type': 'dict[str, Any] | None'},
                                                  'templates': {'canonical': 'templates', 'type': 'list[str]'},
                                                  'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'ProjectItemProxy': {'methods': {},
                                  'properties': {'duration': {'canonical': 'duration', 'type': 'float | None'},
                                                 'filePath': {'canonical': 'file_path', 'type': 'str | None'},
                                                 'file_path': {'canonical': 'file_path', 'type': 'str | None'},
                                                 'frameRate': {'canonical': 'frame_rate', 'type': 'float | None'},
                                                 'frame_rate': {'canonical': 'frame_rate', 'type': 'float | None'},
                                                 'hasAudio': {'canonical': 'has_audio', 'type': 'bool | None'},
                                                 'hasVideo': {'canonical': 'has_video', 'type': 'bool | None'},
                                                 'has_audio': {'canonical': 'has_audio', 'type': 'bool | None'},
                                                 'has_video': {'canonical': 'has_video', 'type': 'bool | None'},
                                                 'height': {'canonical': 'height', 'type': 'int | None'},
                                                 'id': {'canonical': 'id', 'type': 'Any'},
                                                 'index': {'canonical': 'index', 'type': 'int | None'},
                                                 'isActive': {'canonical': 'is_active', 'type': 'bool | None'},
                                                 'is_active': {'canonical': 'is_active', 'type': 'bool | None'},
                                                 'itemType': {'canonical': 'item_type', 'type': 'str | None'},
                                                 'item_type': {'canonical': 'item_type', 'type': 'str | None'},
                                                 'missingFootage': {'canonical': 'missing_footage',
                                                                    'type': 'bool | None'},
                                                 'missing_footage': {'canonical': 'missing_footage',
                                                                     'type': 'bool | None'},
                                                 'name': {'canonical': 'name', 'type': 'str | None'},
                                                 'parentFolderId': {'canonical': 'parent_folder_id', 'type': 'Any'},
                                                 'parentFolderName': {'canonical': 'parent_folder_name',
                                                                      'type': 'str | None'},
                                                 'parent_folder_id': {'canonical': 'parent_folder_id', 'type': 'Any'},
                                                 'parent_folder_name': {'canonical': 'parent_folder_name',
                                                                        'type': 'str | None'},
                                                 'selected': {'canonical': 'selected', 'type': 'bool | None'},
                                                 'typeName': {'canonical': 'type_name', 'type': 'str | None'},
                                                 'type_name': {'canonical': 'type_name', 'type': 'str | None'},
                                                 'typename': {'canonical': 'typename', 'type': 'str | None'},
                                                 'width': {'canonical': 'width', 'type': 'int | None'}}},
             'ProjectProxy': {'methods': {'getItemById': {'canonical': 'getItemById',
                                                          'returns': 'ProjectItemProxy | None'},
                                          'getItemsByName': {'canonical': 'getItemsByName',
                                                             'returns': 'list[ProjectItemProxy]'},
                                          'get_item_by_id': {'canonical': 'getItemById',
                                                             'returns': 'ProjectItemProxy | None'},
                                          'get_items_by_name': {'canonical': 'getItemsByName',
                                                                'returns': 'list[ProjectItemProxy]'}},
                              'properties': {'activeItem': {'canonical': 'active_item',
                                                            'type': 'ProjectItemProxy | None'},
                                             'active_item': {'canonical': 'active_item',
                                                             'type': 'ProjectItemProxy | None'},
                                             'compositions': {'canonical': 'compositions',
                                                              'type': 'list[CompositionProxy]'},
                                             'folders': {'canonical': 'folders', 'type': 'list[FolderItemProxy]'},
                                             'footageItems': {'canonical': 'footage_items',
                                                              'type': 'list[FootageItemProxy]'},
                                             'footage_items': {'canonical': 'footage_items',
                                                               'type': 'list[FootageItemProxy]'},
                                             'itemCount': {'canonical': 'item_count', 'type': 'int | None'},
                                             'item_count': {'canonical': 'item_count', 'type': 'int | None'},
                                             'items': {'canonical': 'items', 'type': 'list[ProjectItemProxy]'},
                                             'name': {'canonical': 'name', 'type': 'str | None'},
                                             'path': {'canonical': 'path', 'type': 'str | None'},
                                             'renderQueue': {'canonical': 'render_queue', 'type': 'RenderQueueProxy'},
                                             'render_queue': {'canonical': 'render_queue', 'type': 'RenderQueueProxy'},
                                             'selectedItems': {'canonical': 'selected_items',
                                                               'type': 'list[ProjectItemProxy]'},
                                             'selected_items': {'canonical': 'selected_items',
                                                                'type': 'list[ProjectItemProxy]'}}},
             'RenderQueueItemProxy': {'methods': {'applyTemplate': {'canonical': 'applyTemplate',
                                                                    'returns': 'RenderQueueItemProxy'},
                                                  'apply_template': {'canonical': 'applyTemplate',
                                                                     'returns': 'RenderQueueItemProxy'},
                                                  'outputModule': {'canonical': 'outputModule',
                                                                   'returns': 'OutputModuleProxy | None'},
                                                  'output_module': {'canonical': 'outputModule',
                                                                    'returns': 'OutputModuleProxy | None'},
                                                  'setQueueItemNotify': {'canonical': 'setQueueItemNotify',
                                                                         'returns': 'RenderQueueItemProxy'},
                                                  'setRender': {'canonical': 'setRender',
                                                                'returns': 'RenderQueueItemProxy'},
                                                  'setSettings': {'canonical': 'setSettings',
                                                                  'returns': 'RenderQueueItemProxy'},
                                                  'set_queue_item_notify': {'canonical': 'setQueueItemNotify',
                                                                            'returns': 'RenderQueueItemProxy'},
                                                  'set_render': {'canonical': 'setRender',
                                                                 'returns': 'RenderQueueItemProxy'},
                                                  'set_settings': {'canonical': 'setSettings',
                                                                   'returns': 'RenderQueueItemProxy'}},
                                      'properties': {'compId': {'canonical': 'comp_id', 'type': 'Any'},
                                                     'compName': {'canonical': 'comp_name', 'type': 'str | None'},
                                                     'comp_id': {'canonical': 'comp_id', 'type': 'Any'},
                                                     'comp_name': {'canonical': 'comp_name', 'type': 'str | None'},
                                                     'elapsedSeconds': {'canonical': 'elapsed_seconds',
                                                                        'type': 'float | None'},
                                                     'elapsed_seconds': {'canonical': 'elapsed_seconds',
                                                                         'type': 'float | None'},
                                                     'id': {'canonical': 'id', 'type': 'Any'},
                                                     'index': {'canonical': 'index', 'type': 'int | None'},
                                                     'numOutputModules': {'canonical': 'num_output_modules',
                                                                          'type': 'int | None'},
                                                     'num_output_modules': {'canonical': 'num_output_modules',
                                                                            'type': 'int | None'},
                                                     'outputModules': {'canonical': 'output_modules',
                                                                       'type': 'list[OutputModuleProxy]'},
                                                     'output_modules': {'canonical': 'output_modules',
                                                                        'type': 'list[OutputModuleProxy]'},
                                                     'queueItemNotify': {'canonical': 'queue_item_notify',
                                                                         'type': 'bool | None'},
                                                     'queue_item_notify': {'canonical': 'queue_item_notify',
                                                                           'type': 'bool | None'},
                                                     'render': {'canonical': 'render', 'type': 'bool | None'},
                                                     'settings': {'canonical': 'settings',
                                                                  'type': 'dict[str, Any] | None'},
                                                     'skipFrames': {'canonical': 'skip_frames', 'type': 'int | None'},
                                                     'skip_frames': {'canonical': 'skip_frames', 'type': 'int | None'},
                                                     'status': {'canonical': 'status', 'type': 'str | None'},
                                                     'templates': {'canonical': 'templates', 'type': 'list[str]'},
                                                     'timeSpanDuration': {'canonical': 'time_span_duration',
                                                                          'type': 'float | None'},
                                                     'timeSpanStart': {'canonical': 'time_span_start',
                                                                       'type': 'float | None'},
                                                     'time_span_duration': {'canonical': 'time_span_duration',
                                                                            'type': 'float | None'},
                                                     'time_span_start': {'canonical': 'time_span_start',
                                                                         'type': 'float | None'},
                                                     'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'RenderQueueProxy': {'methods': {'addComposition': {'canonical': 'addComposition',
                                                                 'returns': 'RenderQueueItemProxy'},
                                              'add_composition': {'canonical': 'addComposition',
                                                                  'returns': 'RenderQueueItemProxy'},
                                              'getItemByIndex': {'canonical': 'getItemByIndex',
                                                                 'returns': 'RenderQueueItemProxy | None'},
                                              'get_item_by_index': {'canonical': 'getItemByIndex',
                                                                    'returns': 'RenderQueueItemProxy | None'},
                                              'pauseRendering': {'canonical': 'pauseRendering',
                                                                 'returns': 'RenderQueueProxy'},
                                              'pause_rendering': {'canonical': 'pauseRendering',
                                                                  'returns': 'RenderQueueProxy'},
                                              'queueInAME': {'canonical': 'queueInAME', 'returns': 'RenderQueueProxy'},
                                              'queueSelectedCompositions': {'canonical': 'queueSelectedCompositions',
                                                                            'returns': 'list[RenderQueueItemProxy]'},
                                              'queue_in_a_m_e': {'canonical': 'queueInAME',
                                                                 'returns': 'RenderQueueProxy'},
                                              'queue_selected_compositions': {'canonical': 'queueSelectedCompositions',
                                                                              'returns': 'list[RenderQueueItemProxy]'},
                                              'render': {'canonical': 'render', 'returns': 'RenderQueueProxy'},
                                              'setQueueNotify': {'canonical': 'setQueueNotify',
                                                                 'returns': 'RenderQueueProxy'},
                                              'set_queue_notify': {'canonical': 'setQueueNotify',
                                                                   'returns': 'RenderQueueProxy'},
                                              'showWindow': {'canonical': 'showWindow', 'returns': 'RenderQueueProxy'},
                                              'show_window': {'canonical': 'showWindow', 'returns': 'RenderQueueProxy'},
                                              'stopRendering': {'canonical': 'stopRendering',
                                                                'returns': 'RenderQueueProxy'},
                                              'stop_rendering': {'canonical': 'stopRendering',
                                                                 'returns': 'RenderQueueProxy'}},
                                  'properties': {'canQueueInAme': {'canonical': 'can_queue_in_ame',
                                                                   'type': 'bool | None'},
                                                 'can_queue_in_ame': {'canonical': 'can_queue_in_ame',
                                                                      'type': 'bool | None'},
                                                 'items': {'canonical': 'items', 'type': 'list[RenderQueueItemProxy]'},
                                                 'numItems': {'canonical': 'num_items', 'type': 'int | None'},
                                                 'num_items': {'canonical': 'num_items', 'type': 'int | None'},
                                                 'queueNotify': {'canonical': 'queue_notify', 'type': 'bool | None'},
                                                 'queue_notify': {'canonical': 'queue_notify', 'type': 'bool | None'},
                                                 'rendering': {'canonical': 'rendering', 'type': 'bool | None'},
                                                 'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'SourceTextProxy': {'methods': {},
                                 'properties': {'fillColor': {'canonical': 'fill_color', 'type': 'Any'},
                                                'fill_color': {'canonical': 'fill_color', 'type': 'Any'},
                                                'font': {'canonical': 'font', 'type': 'str | None'},
                                                'fontSize': {'canonical': 'font_size', 'type': 'float | None'},
                                                'font_size': {'canonical': 'font_size', 'type': 'float | None'},
                                                'justification': {'canonical': 'justification', 'type': 'str | None'},
                                                'strokeColor': {'canonical': 'stroke_color', 'type': 'Any'},
                                                'stroke_color': {'canonical': 'stroke_color', 'type': 'Any'},
                                                'text': {'canonical': 'text', 'type': 'str | None'},
                                                'tracking': {'canonical': 'tracking', 'type': 'Any'},
                                                'typename': {'canonical': 'typename', 'type': 'str | None'}}}},
 'host': 'after-effects',
 'version': '0.1.0'}
