from __future__ import annotations

from typing import Any
from adobe.core import BrokerClient
from adobe.core.session import HostSession

class AfterEffectsSession(HostSession):
    def __init__(self, client: BrokerClient | None = ...) -> None: ...


class AfterEffects(AfterEffectsSession):
    def __init__(self, *, broker_url: str | None = ..., token: str | None = ..., target: str = "default", timeout: float = ..., client: BrokerClient | None = ...) -> None: ...
    @property
    def version(self) -> str: ...
    @property
    def active_project(self) -> ProjectProxy | None: ...
    @property
    def activeProject(self) -> ProjectProxy | None: ...
    @property
    def active_item(self) -> ProjectItemProxy | None: ...
    @property
    def activeItem(self) -> ProjectItemProxy | None: ...
    @property
    def selected_items(self) -> list[ProjectItemProxy]: ...
    @property
    def selectedItems(self) -> list[ProjectItemProxy]: ...


class AfterEffectsApp:
    @property
    def version(self) -> str: ...
    @property
    def active_project(self) -> ProjectProxy | None: ...
    @property
    def activeProject(self) -> ProjectProxy | None: ...
    @property
    def active_item(self) -> ProjectItemProxy | None: ...
    @property
    def activeItem(self) -> ProjectItemProxy | None: ...
    @property
    def selected_items(self) -> list[ProjectItemProxy]: ...
    @property
    def selectedItems(self) -> list[ProjectItemProxy]: ...


class ProjectProxy:
    @property
    def name(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def item_count(self) -> int | None: ...
    @property
    def itemCount(self) -> int | None: ...
    @property
    def items(self) -> list[ProjectItemProxy]: ...
    @property
    def compositions(self) -> list[CompositionProxy]: ...
    @property
    def footage_items(self) -> list[FootageItemProxy]: ...
    @property
    def footageItems(self) -> list[FootageItemProxy]: ...
    @property
    def folders(self) -> list[FolderItemProxy]: ...
    @property
    def active_item(self) -> ProjectItemProxy | None: ...
    @property
    def activeItem(self) -> ProjectItemProxy | None: ...
    @property
    def selected_items(self) -> list[ProjectItemProxy]: ...
    @property
    def selectedItems(self) -> list[ProjectItemProxy]: ...
    def get_item_by_id(self, *args: Any, **kwargs: Any) -> ProjectItemProxy | None: ...
    def getItemById(self, *args: Any, **kwargs: Any) -> ProjectItemProxy | None: ...
    def get_items_by_name(self, *args: Any, **kwargs: Any) -> list[ProjectItemProxy]: ...
    def getItemsByName(self, *args: Any, **kwargs: Any) -> list[ProjectItemProxy]: ...


class ProjectItemProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def type_name(self) -> str | None: ...
    @property
    def typeName(self) -> str | None: ...
    @property
    def item_type(self) -> str | None: ...
    @property
    def itemType(self) -> str | None: ...
    @property
    def parent_folder_id(self) -> Any: ...
    @property
    def parentFolderId(self) -> Any: ...
    @property
    def parent_folder_name(self) -> str | None: ...
    @property
    def parentFolderName(self) -> str | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def is_active(self) -> bool | None: ...
    @property
    def isActive(self) -> bool | None: ...
    @property
    def width(self) -> int | None: ...
    @property
    def height(self) -> int | None: ...
    @property
    def duration(self) -> float | None: ...
    @property
    def frame_rate(self) -> float | None: ...
    @property
    def frameRate(self) -> float | None: ...
    @property
    def has_video(self) -> bool | None: ...
    @property
    def hasVideo(self) -> bool | None: ...
    @property
    def has_audio(self) -> bool | None: ...
    @property
    def hasAudio(self) -> bool | None: ...
    @property
    def file_path(self) -> str | None: ...
    @property
    def filePath(self) -> str | None: ...
    @property
    def missing_footage(self) -> bool | None: ...
    @property
    def missingFootage(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...


class CompositionProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def type_name(self) -> str | None: ...
    @property
    def typeName(self) -> str | None: ...
    @property
    def item_type(self) -> str | None: ...
    @property
    def itemType(self) -> str | None: ...
    @property
    def parent_folder_id(self) -> Any: ...
    @property
    def parentFolderId(self) -> Any: ...
    @property
    def parent_folder_name(self) -> str | None: ...
    @property
    def parentFolderName(self) -> str | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def is_active(self) -> bool | None: ...
    @property
    def isActive(self) -> bool | None: ...
    @property
    def width(self) -> int | None: ...
    @property
    def height(self) -> int | None: ...
    @property
    def duration(self) -> float | None: ...
    @property
    def frame_rate(self) -> float | None: ...
    @property
    def frameRate(self) -> float | None: ...
    @property
    def num_layers(self) -> int | None: ...
    @property
    def numLayers(self) -> int | None: ...
    @property
    def work_area_start(self) -> float | None: ...
    @property
    def workAreaStart(self) -> float | None: ...
    @property
    def work_area_duration(self) -> float | None: ...
    @property
    def workAreaDuration(self) -> float | None: ...
    @property
    def layers(self) -> list[LayerProxy]: ...
    @property
    def selected_layers(self) -> list[LayerProxy]: ...
    @property
    def selectedLayers(self) -> list[LayerProxy]: ...
    @property
    def typename(self) -> str | None: ...
    def get_layer_by_id(self, *args: Any, **kwargs: Any) -> LayerProxy | None: ...
    def getLayerById(self, *args: Any, **kwargs: Any) -> LayerProxy | None: ...


class FootageItemProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def type_name(self) -> str | None: ...
    @property
    def typeName(self) -> str | None: ...
    @property
    def item_type(self) -> str | None: ...
    @property
    def itemType(self) -> str | None: ...
    @property
    def parent_folder_id(self) -> Any: ...
    @property
    def parentFolderId(self) -> Any: ...
    @property
    def parent_folder_name(self) -> str | None: ...
    @property
    def parentFolderName(self) -> str | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def is_active(self) -> bool | None: ...
    @property
    def isActive(self) -> bool | None: ...
    @property
    def width(self) -> int | None: ...
    @property
    def height(self) -> int | None: ...
    @property
    def duration(self) -> float | None: ...
    @property
    def frame_rate(self) -> float | None: ...
    @property
    def frameRate(self) -> float | None: ...
    @property
    def has_video(self) -> bool | None: ...
    @property
    def hasVideo(self) -> bool | None: ...
    @property
    def has_audio(self) -> bool | None: ...
    @property
    def hasAudio(self) -> bool | None: ...
    @property
    def file_path(self) -> str | None: ...
    @property
    def filePath(self) -> str | None: ...
    @property
    def missing_footage(self) -> bool | None: ...
    @property
    def missingFootage(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...


class FolderItemProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def type_name(self) -> str | None: ...
    @property
    def typeName(self) -> str | None: ...
    @property
    def item_type(self) -> str | None: ...
    @property
    def itemType(self) -> str | None: ...
    @property
    def parent_folder_id(self) -> Any: ...
    @property
    def parentFolderId(self) -> Any: ...
    @property
    def parent_folder_name(self) -> str | None: ...
    @property
    def parentFolderName(self) -> str | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def is_active(self) -> bool | None: ...
    @property
    def isActive(self) -> bool | None: ...
    @property
    def item_count(self) -> int | None: ...
    @property
    def itemCount(self) -> int | None: ...
    @property
    def typename(self) -> str | None: ...


class LayerProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def type_name(self) -> str | None: ...
    @property
    def typeName(self) -> str | None: ...
    @property
    def layer_type(self) -> str | None: ...
    @property
    def layerType(self) -> str | None: ...
    @property
    def comp_id(self) -> Any: ...
    @property
    def compId(self) -> Any: ...
    @property
    def source_id(self) -> Any: ...
    @property
    def sourceId(self) -> Any: ...
    @property
    def source_name(self) -> str | None: ...
    @property
    def sourceName(self) -> str | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def enabled(self) -> bool | None: ...
    @property
    def solo(self) -> bool | None: ...
    @property
    def locked(self) -> bool | None: ...
    @property
    def shy(self) -> bool | None: ...
    @property
    def is_text(self) -> bool | None: ...
    @property
    def isText(self) -> bool | None: ...
    @property
    def start_time(self) -> float | None: ...
    @property
    def startTime(self) -> float | None: ...
    @property
    def in_point(self) -> float | None: ...
    @property
    def inPoint(self) -> float | None: ...
    @property
    def out_point(self) -> float | None: ...
    @property
    def outPoint(self) -> float | None: ...
    @property
    def stretch(self) -> float | None: ...
    @property
    def width(self) -> int | None: ...
    @property
    def height(self) -> int | None: ...
    @property
    def has_video(self) -> bool | None: ...
    @property
    def hasVideo(self) -> bool | None: ...
    @property
    def has_audio(self) -> bool | None: ...
    @property
    def hasAudio(self) -> bool | None: ...
    @property
    def effects(self) -> list[EffectProxy]: ...
    @property
    def masks(self) -> list[MaskProxy]: ...
    @property
    def source_text(self) -> SourceTextProxy | None: ...
    @property
    def sourceText(self) -> SourceTextProxy | None: ...
    @property
    def typename(self) -> str | None: ...
    def get_effect(self, *args: Any, **kwargs: Any) -> EffectProxy | None: ...
    def getEffect(self, *args: Any, **kwargs: Any) -> EffectProxy | None: ...
    def set_source_text(self, *args: Any, **kwargs: Any) -> SourceTextProxy: ...
    def setSourceText(self, *args: Any, **kwargs: Any) -> SourceTextProxy: ...


class MaskProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def mask_mode(self) -> str | None: ...
    @property
    def maskMode(self) -> str | None: ...
    @property
    def inverted(self) -> bool | None: ...
    @property
    def locked(self) -> bool | None: ...
    @property
    def roto_bezier(self) -> bool | None: ...
    @property
    def rotoBezier(self) -> bool | None: ...
    @property
    def opacity(self) -> Any: ...
    @property
    def feather(self) -> Any: ...
    @property
    def expansion(self) -> Any: ...
    @property
    def typename(self) -> str | None: ...


class EffectProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def match_name(self) -> str | None: ...
    @property
    def matchName(self) -> str | None: ...
    @property
    def enabled(self) -> bool | None: ...
    @property
    def active(self) -> bool | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def property_count(self) -> int | None: ...
    @property
    def propertyCount(self) -> int | None: ...
    @property
    def typename(self) -> str | None: ...


class SourceTextProxy:
    @property
    def text(self) -> str | None: ...
    @property
    def font(self) -> str | None: ...
    @property
    def font_size(self) -> float | None: ...
    @property
    def fontSize(self) -> float | None: ...
    @property
    def fill_color(self) -> Any: ...
    @property
    def fillColor(self) -> Any: ...
    @property
    def stroke_color(self) -> Any: ...
    @property
    def strokeColor(self) -> Any: ...
    @property
    def tracking(self) -> Any: ...
    @property
    def justification(self) -> str | None: ...
    @property
    def typename(self) -> str | None: ...
