# Generated from generators/ir by generators/ir_to_python.py.
# Do not edit by hand; run `npm run facades:write`.
from __future__ import annotations

FACADE_CONTRACT = {'capabilities': {'bridgeKind': 'generated',
                  'bridgeVersion': '0.1.0',
                  'features': [],
                  'host': 'indesign',
                  'methods': {'app': ['getVersion'],
                              'document': ['getActive'],
                              'export': ['exportFile'],
                              'link': ['getLinks', 'getByName', 'update', 'relink'],
                              'package': ['packageForPrint'],
                              'page': ['getPages', 'getActive', 'getByName', 'select'],
                              'raw': ['evalJs'],
                              'spread': ['getSpreads', 'getActive', 'getByName'],
                              'story': ['getStories', 'getByName', 'getByTextFrameId', 'setContents'],
                              'style': ['getParagraphStyles',
                                        'getCharacterStyles',
                                        'getParagraphStyleByName',
                                        'getCharacterStyleByName',
                                        'setParagraphStyleProperties',
                                        'setCharacterStyleProperties'],
                              'swatch': ['getSwatches', 'getByName', 'addColor'],
                              'text': ['getTextFrames', 'getTextFrameByName', 'getSelectedText', 'setFrameContents']},
                  'namespaces': ['app',
                                 'document',
                                 'page',
                                 'spread',
                                 'text',
                                 'story',
                                 'style',
                                 'swatch',
                                 'link',
                                 'export',
                                 'package',
                                 'raw']},
 'classes': {'CharacterStyleProxy': {'methods': {'update': {'canonical': 'update', 'returns': 'CharacterStyleProxy'}},
                                     'properties': {'appliedFont': {'canonical': 'applied_font', 'type': 'Any'},
                                                    'applied_font': {'canonical': 'applied_font', 'type': 'Any'},
                                                    'fontStyle': {'canonical': 'font_style', 'type': 'Any'},
                                                    'font_style': {'canonical': 'font_style', 'type': 'Any'},
                                                    'id': {'canonical': 'id', 'type': 'int | str | None'},
                                                    'index': {'canonical': 'index', 'type': 'Any'},
                                                    'isValid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                                    'is_valid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                                    'leading': {'canonical': 'leading', 'type': 'Any'},
                                                    'name': {'canonical': 'name', 'type': 'str | None'},
                                                    'pointSize': {'canonical': 'point_size', 'type': 'Any'},
                                                    'point_size': {'canonical': 'point_size', 'type': 'Any'},
                                                    'tracking': {'canonical': 'tracking', 'type': 'Any'},
                                                    'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'DocumentExportProxy': {'methods': {'epub': {'canonical': 'epub', 'returns': 'Any'},
                                                 'file': {'canonical': 'file', 'returns': 'Any'},
                                                 'idml': {'canonical': 'idml', 'returns': 'Any'},
                                                 'interactivePdf': {'canonical': 'interactivePdf', 'returns': 'Any'},
                                                 'interactive_pdf': {'canonical': 'interactivePdf', 'returns': 'Any'},
                                                 'pdf': {'canonical': 'pdf', 'returns': 'Any'}},
                                     'properties': {}},
             'DocumentPackageProxy': {'methods': {'forPrint': {'canonical': 'forPrint', 'returns': 'dict[str, Any]'},
                                                  'for_print': {'canonical': 'forPrint', 'returns': 'dict[str, Any]'}},
                                      'properties': {}},
             'DocumentProxy': {'methods': {'addColorSwatch': {'canonical': 'addColorSwatch', 'returns': 'SwatchProxy'},
                                           'add_color_swatch': {'canonical': 'addColorSwatch',
                                                                'returns': 'SwatchProxy'},
                                           'exportFile': {'canonical': 'exportFile', 'returns': 'Any'},
                                           'export_file': {'canonical': 'exportFile', 'returns': 'Any'},
                                           'getCharacterStyle': {'canonical': 'getCharacterStyle',
                                                                 'returns': 'CharacterStyleProxy | None'},
                                           'getLink': {'canonical': 'getLink', 'returns': 'LinkProxy | None'},
                                           'getPage': {'canonical': 'getPage', 'returns': 'PageProxy | None'},
                                           'getParagraphStyle': {'canonical': 'getParagraphStyle',
                                                                 'returns': 'ParagraphStyleProxy | None'},
                                           'getSpread': {'canonical': 'getSpread', 'returns': 'SpreadProxy | None'},
                                           'getStory': {'canonical': 'getStory', 'returns': 'StoryProxy | None'},
                                           'getSwatch': {'canonical': 'getSwatch', 'returns': 'SwatchProxy | None'},
                                           'getTextFrame': {'canonical': 'getTextFrame',
                                                            'returns': 'TextFrameProxy | None'},
                                           'get_character_style': {'canonical': 'getCharacterStyle',
                                                                   'returns': 'CharacterStyleProxy | None'},
                                           'get_link': {'canonical': 'getLink', 'returns': 'LinkProxy | None'},
                                           'get_page': {'canonical': 'getPage', 'returns': 'PageProxy | None'},
                                           'get_paragraph_style': {'canonical': 'getParagraphStyle',
                                                                   'returns': 'ParagraphStyleProxy | None'},
                                           'get_spread': {'canonical': 'getSpread', 'returns': 'SpreadProxy | None'},
                                           'get_story': {'canonical': 'getStory', 'returns': 'StoryProxy | None'},
                                           'get_swatch': {'canonical': 'getSwatch', 'returns': 'SwatchProxy | None'},
                                           'get_text_frame': {'canonical': 'getTextFrame',
                                                              'returns': 'TextFrameProxy | None'},
                                           'packageForPrint': {'canonical': 'packageForPrint',
                                                               'returns': 'dict[str, Any]'},
                                           'package_for_print': {'canonical': 'packageForPrint',
                                                                 'returns': 'dict[str, Any]'}},
                               'properties': {'activePage': {'canonical': 'active_page', 'type': 'PageProxy | None'},
                                              'activeSpread': {'canonical': 'active_spread',
                                                               'type': 'SpreadProxy | None'},
                                              'active_page': {'canonical': 'active_page', 'type': 'PageProxy | None'},
                                              'active_spread': {'canonical': 'active_spread',
                                                                'type': 'SpreadProxy | None'},
                                              'characterStyles': {'canonical': 'character_styles',
                                                                  'type': 'list[CharacterStyleProxy]'},
                                              'character_styles': {'canonical': 'character_styles',
                                                                   'type': 'list[CharacterStyleProxy]'},
                                              'exports': {'canonical': 'exports', 'type': 'DocumentExportProxy'},
                                              'height': {'canonical': 'height', 'type': 'Any'},
                                              'id': {'canonical': 'id', 'type': 'int | str | None'},
                                              'links': {'canonical': 'links', 'type': 'list[LinkProxy]'},
                                              'name': {'canonical': 'name', 'type': 'str | None'},
                                              'package': {'canonical': 'package', 'type': 'DocumentPackageProxy'},
                                              'pageCount': {'canonical': 'page_count', 'type': 'int'},
                                              'page_count': {'canonical': 'page_count', 'type': 'int'},
                                              'pages': {'canonical': 'pages', 'type': 'list[PageProxy]'},
                                              'paragraphStyles': {'canonical': 'paragraph_styles',
                                                                  'type': 'list[ParagraphStyleProxy]'},
                                              'paragraph_styles': {'canonical': 'paragraph_styles',
                                                                   'type': 'list[ParagraphStyleProxy]'},
                                              'path': {'canonical': 'path', 'type': 'str | None'},
                                              'spreadCount': {'canonical': 'spread_count', 'type': 'int'},
                                              'spread_count': {'canonical': 'spread_count', 'type': 'int'},
                                              'spreads': {'canonical': 'spreads', 'type': 'list[SpreadProxy]'},
                                              'stories': {'canonical': 'stories', 'type': 'list[StoryProxy]'},
                                              'swatches': {'canonical': 'swatches', 'type': 'list[SwatchProxy]'},
                                              'textFrames': {'canonical': 'text_frames',
                                                             'type': 'list[TextFrameProxy]'},
                                              'text_frames': {'canonical': 'text_frames',
                                                              'type': 'list[TextFrameProxy]'},
                                              'typename': {'canonical': 'typename', 'type': 'str | None'},
                                              'width': {'canonical': 'width', 'type': 'Any'}}},
             'InDesign': {'methods': {},
                          'properties': {'activeDocument': {'canonical': 'active_document',
                                                            'mutatesState': False,
                                                            'raw': False,
                                                            'requiresModalWhenMutating': False,
                                                            'source': 'document.getActive',
                                                            'type': 'DocumentProxy | None'},
                                         'activePage': {'canonical': 'active_page',
                                                        'mutatesState': False,
                                                        'raw': False,
                                                        'requiresModalWhenMutating': False,
                                                        'source': 'page.getActive',
                                                        'type': 'PageProxy | None'},
                                         'activeSpread': {'canonical': 'active_spread',
                                                          'mutatesState': False,
                                                          'raw': False,
                                                          'requiresModalWhenMutating': False,
                                                          'source': 'spread.getActive',
                                                          'type': 'SpreadProxy | None'},
                                         'active_document': {'canonical': 'active_document',
                                                             'mutatesState': False,
                                                             'raw': False,
                                                             'requiresModalWhenMutating': False,
                                                             'source': 'document.getActive',
                                                             'type': 'DocumentProxy | None'},
                                         'active_page': {'canonical': 'active_page',
                                                         'mutatesState': False,
                                                         'raw': False,
                                                         'requiresModalWhenMutating': False,
                                                         'source': 'page.getActive',
                                                         'type': 'PageProxy | None'},
                                         'active_spread': {'canonical': 'active_spread',
                                                           'mutatesState': False,
                                                           'raw': False,
                                                           'requiresModalWhenMutating': False,
                                                           'source': 'spread.getActive',
                                                           'type': 'SpreadProxy | None'},
                                         'selectedText': {'canonical': 'selected_text',
                                                          'mutatesState': False,
                                                          'raw': False,
                                                          'requiresModalWhenMutating': False,
                                                          'source': 'text.getSelectedText',
                                                          'type': 'TextSelectionProxy | None'},
                                         'selected_text': {'canonical': 'selected_text',
                                                           'mutatesState': False,
                                                           'raw': False,
                                                           'requiresModalWhenMutating': False,
                                                           'source': 'text.getSelectedText',
                                                           'type': 'TextSelectionProxy | None'},
                                         'version': {'canonical': 'version',
                                                     'mutatesState': False,
                                                     'raw': False,
                                                     'requiresModalWhenMutating': False,
                                                     'source': 'app.getVersion',
                                                     'type': 'str'}}},
             'InDesignApp': {'methods': {},
                             'properties': {'activeDocument': {'canonical': 'active_document',
                                                               'mutatesState': False,
                                                               'raw': False,
                                                               'requiresModalWhenMutating': False,
                                                               'source': 'document.getActive',
                                                               'type': 'DocumentProxy | None'},
                                            'activePage': {'canonical': 'active_page',
                                                           'mutatesState': False,
                                                           'raw': False,
                                                           'requiresModalWhenMutating': False,
                                                           'source': 'page.getActive',
                                                           'type': 'PageProxy | None'},
                                            'activeSpread': {'canonical': 'active_spread',
                                                             'mutatesState': False,
                                                             'raw': False,
                                                             'requiresModalWhenMutating': False,
                                                             'source': 'spread.getActive',
                                                             'type': 'SpreadProxy | None'},
                                            'active_document': {'canonical': 'active_document',
                                                                'mutatesState': False,
                                                                'raw': False,
                                                                'requiresModalWhenMutating': False,
                                                                'source': 'document.getActive',
                                                                'type': 'DocumentProxy | None'},
                                            'active_page': {'canonical': 'active_page',
                                                            'mutatesState': False,
                                                            'raw': False,
                                                            'requiresModalWhenMutating': False,
                                                            'source': 'page.getActive',
                                                            'type': 'PageProxy | None'},
                                            'active_spread': {'canonical': 'active_spread',
                                                              'mutatesState': False,
                                                              'raw': False,
                                                              'requiresModalWhenMutating': False,
                                                              'source': 'spread.getActive',
                                                              'type': 'SpreadProxy | None'},
                                            'selectedText': {'canonical': 'selected_text',
                                                             'mutatesState': False,
                                                             'raw': False,
                                                             'requiresModalWhenMutating': False,
                                                             'source': 'text.getSelectedText',
                                                             'type': 'TextSelectionProxy | None'},
                                            'selected_text': {'canonical': 'selected_text',
                                                              'mutatesState': False,
                                                              'raw': False,
                                                              'requiresModalWhenMutating': False,
                                                              'source': 'text.getSelectedText',
                                                              'type': 'TextSelectionProxy | None'},
                                            'version': {'canonical': 'version',
                                                        'mutatesState': False,
                                                        'raw': False,
                                                        'requiresModalWhenMutating': False,
                                                        'source': 'app.getVersion',
                                                        'type': 'str'}}},
             'LinkProxy': {'methods': {'relink': {'canonical': 'relink', 'returns': 'LinkProxy'},
                                       'update': {'canonical': 'update', 'returns': 'LinkProxy'}},
                           'properties': {'filePath': {'canonical': 'file_path', 'type': 'str | None'},
                                          'file_path': {'canonical': 'file_path', 'type': 'str | None'},
                                          'id': {'canonical': 'id', 'type': 'int | str | None'},
                                          'isValid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                          'is_valid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                          'linkType': {'canonical': 'link_type', 'type': 'str | None'},
                                          'link_type': {'canonical': 'link_type', 'type': 'str | None'},
                                          'name': {'canonical': 'name', 'type': 'str | None'},
                                          'status': {'canonical': 'status', 'type': 'Any'},
                                          'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'PageProxy': {'methods': {'select': {'canonical': 'select', 'returns': 'PageProxy'}},
                           'properties': {'bounds': {'canonical': 'bounds', 'type': 'list[Any]'},
                                          'documentOffset': {'canonical': 'document_offset', 'type': 'Any'},
                                          'document_offset': {'canonical': 'document_offset', 'type': 'Any'},
                                          'id': {'canonical': 'id', 'type': 'int | str | None'},
                                          'index': {'canonical': 'index', 'type': 'Any'},
                                          'isValid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                          'is_valid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                          'name': {'canonical': 'name', 'type': 'str | None'},
                                          'parentId': {'canonical': 'parent_id', 'type': 'int | str | None'},
                                          'parentName': {'canonical': 'parent_name', 'type': 'str | None'},
                                          'parent_id': {'canonical': 'parent_id', 'type': 'int | str | None'},
                                          'parent_name': {'canonical': 'parent_name', 'type': 'str | None'},
                                          'side': {'canonical': 'side', 'type': 'Any'},
                                          'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'ParagraphStyleProxy': {'methods': {'update': {'canonical': 'update', 'returns': 'ParagraphStyleProxy'}},
                                     'properties': {'appliedFont': {'canonical': 'applied_font', 'type': 'Any'},
                                                    'applied_font': {'canonical': 'applied_font', 'type': 'Any'},
                                                    'fontStyle': {'canonical': 'font_style', 'type': 'Any'},
                                                    'font_style': {'canonical': 'font_style', 'type': 'Any'},
                                                    'id': {'canonical': 'id', 'type': 'int | str | None'},
                                                    'index': {'canonical': 'index', 'type': 'Any'},
                                                    'isValid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                                    'is_valid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                                    'justification': {'canonical': 'justification', 'type': 'Any'},
                                                    'leading': {'canonical': 'leading', 'type': 'Any'},
                                                    'name': {'canonical': 'name', 'type': 'str | None'},
                                                    'pointSize': {'canonical': 'point_size', 'type': 'Any'},
                                                    'point_size': {'canonical': 'point_size', 'type': 'Any'},
                                                    'tracking': {'canonical': 'tracking', 'type': 'Any'},
                                                    'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'SpreadProxy': {'methods': {},
                             'properties': {'id': {'canonical': 'id', 'type': 'int | str | None'},
                                            'index': {'canonical': 'index', 'type': 'Any'},
                                            'isValid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                            'is_valid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                            'label': {'canonical': 'label', 'type': 'str | None'},
                                            'name': {'canonical': 'name', 'type': 'str | None'},
                                            'pageCount': {'canonical': 'page_count', 'type': 'int'},
                                            'pageNames': {'canonical': 'page_names', 'type': 'list[str]'},
                                            'page_count': {'canonical': 'page_count', 'type': 'int'},
                                            'page_names': {'canonical': 'page_names', 'type': 'list[str]'},
                                            'parentId': {'canonical': 'parent_id', 'type': 'int | str | None'},
                                            'parentName': {'canonical': 'parent_name', 'type': 'str | None'},
                                            'parent_id': {'canonical': 'parent_id', 'type': 'int | str | None'},
                                            'parent_name': {'canonical': 'parent_name', 'type': 'str | None'},
                                            'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'StoryProxy': {'methods': {'setContents': {'canonical': 'setContents', 'returns': 'StoryProxy'},
                                        'set_contents': {'canonical': 'setContents', 'returns': 'StoryProxy'}},
                            'properties': {'contents': {'canonical': 'contents', 'type': 'str | None'},
                                           'id': {'canonical': 'id', 'type': 'int | str | None'},
                                           'index': {'canonical': 'index', 'type': 'Any'},
                                           'isValid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                           'is_valid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                           'length': {'canonical': 'length', 'type': 'Any'},
                                           'name': {'canonical': 'name', 'type': 'str | None'},
                                           'paragraphCount': {'canonical': 'paragraph_count', 'type': 'int'},
                                           'paragraph_count': {'canonical': 'paragraph_count', 'type': 'int'},
                                           'textContainerCount': {'canonical': 'text_container_count', 'type': 'int'},
                                           'text_container_count': {'canonical': 'text_container_count', 'type': 'int'},
                                           'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'SwatchProxy': {'methods': {},
                             'properties': {'colorValue': {'canonical': 'color_value', 'type': 'list[Any]'},
                                            'color_value': {'canonical': 'color_value', 'type': 'list[Any]'},
                                            'id': {'canonical': 'id', 'type': 'int | str | None'},
                                            'isValid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                            'is_valid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                            'model': {'canonical': 'model', 'type': 'Any'},
                                            'name': {'canonical': 'name', 'type': 'str | None'},
                                            'space': {'canonical': 'space', 'type': 'Any'},
                                            'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'TextFrameProxy': {'methods': {'setContents': {'canonical': 'setContents', 'returns': 'TextFrameProxy'},
                                            'set_contents': {'canonical': 'setContents', 'returns': 'TextFrameProxy'}},
                                'properties': {'contents': {'canonical': 'contents', 'type': 'str | None'},
                                               'geometricBounds': {'canonical': 'geometric_bounds',
                                                                   'type': 'list[Any]'},
                                               'geometric_bounds': {'canonical': 'geometric_bounds',
                                                                    'type': 'list[Any]'},
                                               'id': {'canonical': 'id', 'type': 'int | str | None'},
                                               'index': {'canonical': 'index', 'type': 'Any'},
                                               'isValid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                               'is_valid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                               'name': {'canonical': 'name', 'type': 'str | None'},
                                               'overflows': {'canonical': 'overflows', 'type': 'bool | None'},
                                               'parentPageId': {'canonical': 'parent_page_id',
                                                                'type': 'int | str | None'},
                                               'parentPageName': {'canonical': 'parent_page_name',
                                                                  'type': 'str | None'},
                                               'parentStoryId': {'canonical': 'parent_story_id',
                                                                 'type': 'int | str | None'},
                                               'parentStoryName': {'canonical': 'parent_story_name',
                                                                   'type': 'str | None'},
                                               'parent_page_id': {'canonical': 'parent_page_id',
                                                                  'type': 'int | str | None'},
                                               'parent_page_name': {'canonical': 'parent_page_name',
                                                                    'type': 'str | None'},
                                               'parent_story_id': {'canonical': 'parent_story_id',
                                                                   'type': 'int | str | None'},
                                               'parent_story_name': {'canonical': 'parent_story_name',
                                                                     'type': 'str | None'},
                                               'story': {'canonical': 'story', 'type': 'StoryProxy | None'},
                                               'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'TextSelectionProxy': {'methods': {},
                                    'properties': {'contents': {'canonical': 'contents', 'type': 'str | None'},
                                                   'index': {'canonical': 'index', 'type': 'Any'},
                                                   'isValid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                                   'is_valid': {'canonical': 'is_valid', 'type': 'bool | None'},
                                                   'length': {'canonical': 'length', 'type': 'Any'},
                                                   'parentStoryId': {'canonical': 'parent_story_id',
                                                                     'type': 'int | str | None'},
                                                   'parentStoryName': {'canonical': 'parent_story_name',
                                                                       'type': 'str | None'},
                                                   'parent_story_id': {'canonical': 'parent_story_id',
                                                                       'type': 'int | str | None'},
                                                   'parent_story_name': {'canonical': 'parent_story_name',
                                                                         'type': 'str | None'},
                                                   'typename': {'canonical': 'typename', 'type': 'str | None'}}}},
 'host': 'indesign',
 'version': '0.1.0'}
