from __future__ import annotations

from .capabilities import HostCapabilities, normalize_capability_sessions
from .client import BrokerClient
from .dom import DomNamespace, DomObject
from .errors import (
    AdobePythonError,
    BridgeNotInstalledError,
    BrokerConnectionError,
    CapabilityError,
    HostNotRunningError,
    HostScriptError,
    IdentityAmbiguousError,
    IdentityMismatchError,
    IdentityStaleError,
    IdentityUnavailableError,
    MethodNotFoundError,
    ModalRequiredError,
    PermissionError,
    SerializationError,
    TimeoutError,
    UnauthorizedError,
)
from .illustrator_bootstrap import (
    IllustratorAdapterContinuation,
    IllustratorBootstrapContinuation,
    IllustratorBootstrapRequest,
    IllustratorBootstrapResult,
    IllustratorBrokerBinding,
    IllustratorHostBinding,
    IllustratorHostTarget,
    IllustratorPluginBinding,
    IllustratorPluginTarget,
)
from .after_effects_bootstrap import (
    AfterEffectsBootstrapContinuation,
    AfterEffectsBootstrapRequest,
    AfterEffectsBootstrapResult,
)
from .photoshop_bootstrap import (
    PhotoshopBootstrapContinuation,
    PhotoshopBootstrapRequest,
    PhotoshopBootstrapResult,
    PhotoshopHostTarget,
    PhotoshopPluginTarget,
)
from .runtime_identity import (
    BridgeRuntimeIdentity,
    BrokerRuntimeIdentity,
    HostRuntimeIdentity,
    RuntimeIdentityAttestation,
)
from .session import HostSession, connect

__all__ = [
    "AdobePythonError",
    "BridgeNotInstalledError",
    "BridgeRuntimeIdentity",
    "BrokerClient",
    "BrokerConnectionError",
    "BrokerRuntimeIdentity",
    "CapabilityError",
    "DomNamespace",
    "DomObject",
    "HostCapabilities",
    "HostNotRunningError",
    "HostRuntimeIdentity",
    "HostScriptError",
    "HostSession",
    "IdentityAmbiguousError",
    "IdentityMismatchError",
    "IdentityStaleError",
    "IdentityUnavailableError",
    "AfterEffectsBootstrapContinuation",
    "AfterEffectsBootstrapRequest",
    "AfterEffectsBootstrapResult",
    "IllustratorAdapterContinuation",
    "IllustratorBootstrapContinuation",
    "IllustratorBootstrapRequest",
    "IllustratorBootstrapResult",
    "IllustratorBrokerBinding",
    "IllustratorHostBinding",
    "IllustratorHostTarget",
    "IllustratorPluginBinding",
    "IllustratorPluginTarget",
    "MethodNotFoundError",
    "ModalRequiredError",
    "PermissionError",
    "PhotoshopBootstrapContinuation",
    "PhotoshopBootstrapRequest",
    "PhotoshopBootstrapResult",
    "PhotoshopHostTarget",
    "PhotoshopPluginTarget",
    "RuntimeIdentityAttestation",
    "SerializationError",
    "TimeoutError",
    "UnauthorizedError",
    "connect",
    "normalize_capability_sessions",
]
