# Generated from generators/ir by generators/ir_to_python.py.
# Do not edit by hand; run `npm run facades:write`.
from __future__ import annotations

FACADE_CONTRACT = {'capabilities': {'bridgeKind': 'generated',
                  'bridgeVersion': '0.1.0',
                  'features': [],
                  'host': 'premiere',
                  'methods': {'app': ['getVersion'],
                              'bin': ['create'],
                              'clip': ['getSelected'],
                              'encoder': ['getManager',
                                          'getPresets',
                                          'getExportFileExtension',
                                          'encodeFile',
                                          'encodeProjectItem',
                                          'exportSequence'],
                              'export': ['getExporter', 'exportFrame'],
                              'marker': ['getMarkers', 'create'],
                              'project': ['getActive',
                                          'getSequences',
                                          'getActiveSequence',
                                          'getRootItem',
                                          'importFiles'],
                              'projectItem': ['getChildren', 'getSelected', 'findByMediaPath'],
                              'raw': ['evalJs'],
                              'sequence': ['getVideoTracks', 'getAudioTracks'],
                              'track': ['getClips']},
                  'namespaces': ['app',
                                 'project',
                                 'sequence',
                                 'track',
                                 'clip',
                                 'projectItem',
                                 'bin',
                                 'marker',
                                 'encoder',
                                 'export',
                                 'raw']},
 'classes': {'ClipProxy': {'methods': {},
                           'properties': {'duration': {'canonical': 'duration', 'type': 'Any'},
                                          'end': {'canonical': 'end', 'type': 'Any'},
                                          'id': {'canonical': 'id', 'type': 'Any'},
                                          'inPoint': {'canonical': 'in_point', 'type': 'Any'},
                                          'in_point': {'canonical': 'in_point', 'type': 'Any'},
                                          'isEnabled': {'canonical': 'is_enabled', 'type': 'bool | None'},
                                          'isSelected': {'canonical': 'is_selected', 'type': 'bool | None'},
                                          'is_enabled': {'canonical': 'is_enabled', 'type': 'bool | None'},
                                          'is_selected': {'canonical': 'is_selected', 'type': 'bool | None'},
                                          'mediaPath': {'canonical': 'media_path', 'type': 'str | None'},
                                          'media_path': {'canonical': 'media_path', 'type': 'str | None'},
                                          'name': {'canonical': 'name', 'type': 'str | None'},
                                          'outPoint': {'canonical': 'out_point', 'type': 'Any'},
                                          'out_point': {'canonical': 'out_point', 'type': 'Any'},
                                          'projectItemId': {'canonical': 'project_item_id', 'type': 'Any'},
                                          'project_item_id': {'canonical': 'project_item_id', 'type': 'Any'},
                                          'start': {'canonical': 'start', 'type': 'Any'},
                                          'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'EncoderPreset': {'methods': {},
                               'properties': {'extension': {'canonical': 'extension', 'type': 'str | None'},
                                              'format': {'canonical': 'format', 'type': 'str | None'},
                                              'name': {'canonical': 'name', 'type': 'str | None'},
                                              'path': {'canonical': 'path', 'type': 'str | None'},
                                              'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'ExportJob': {'methods': {},
                           'properties': {'exportType': {'canonical': 'export_type', 'type': 'str | None'},
                                          'export_type': {'canonical': 'export_type', 'type': 'str | None'},
                                          'id': {'canonical': 'id', 'type': 'Any'},
                                          'jobId': {'canonical': 'job_id', 'type': 'Any'},
                                          'job_id': {'canonical': 'job_id', 'type': 'Any'},
                                          'outputPath': {'canonical': 'output_path', 'type': 'str | None'},
                                          'output_path': {'canonical': 'output_path', 'type': 'str | None'},
                                          'presetPath': {'canonical': 'preset_path', 'type': 'str | None'},
                                          'preset_path': {'canonical': 'preset_path', 'type': 'str | None'},
                                          'removeOnCompletion': {'canonical': 'remove_on_completion',
                                                                 'type': 'bool | None'},
                                          'remove_on_completion': {'canonical': 'remove_on_completion',
                                                                   'type': 'bool | None'},
                                          'sourceId': {'canonical': 'source_id', 'type': 'Any'},
                                          'sourceName': {'canonical': 'source_name', 'type': 'str | None'},
                                          'source_id': {'canonical': 'source_id', 'type': 'Any'},
                                          'source_name': {'canonical': 'source_name', 'type': 'str | None'},
                                          'started': {'canonical': 'started', 'type': 'bool | None'},
                                          'status': {'canonical': 'status', 'type': 'str | None'},
                                          'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'MarkerProxy': {'methods': {},
                             'properties': {'comments': {'canonical': 'comments', 'type': 'str | None'},
                                            'duration': {'canonical': 'duration', 'type': 'Any'},
                                            'end': {'canonical': 'end', 'type': 'Any'},
                                            'id': {'canonical': 'id', 'type': 'Any'},
                                            'markerType': {'canonical': 'marker_type', 'type': 'str | None'},
                                            'marker_type': {'canonical': 'marker_type', 'type': 'str | None'},
                                            'name': {'canonical': 'name', 'type': 'str | None'},
                                            'start': {'canonical': 'start', 'type': 'Any'},
                                            'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'Premiere': {'methods': {},
                          'properties': {'activeProject': {'canonical': 'active_project',
                                                           'mutatesState': False,
                                                           'raw': False,
                                                           'requiresModalWhenMutating': False,
                                                           'source': 'project.getActive',
                                                           'type': 'ProjectProxy | None'},
                                         'activeSequence': {'canonical': 'active_sequence',
                                                            'mutatesState': False,
                                                            'raw': False,
                                                            'requiresModalWhenMutating': False,
                                                            'source': 'project.getActiveSequence',
                                                            'type': 'SequenceProxy | None'},
                                         'active_project': {'canonical': 'active_project',
                                                            'mutatesState': False,
                                                            'raw': False,
                                                            'requiresModalWhenMutating': False,
                                                            'source': 'project.getActive',
                                                            'type': 'ProjectProxy | None'},
                                         'active_sequence': {'canonical': 'active_sequence',
                                                             'mutatesState': False,
                                                             'raw': False,
                                                             'requiresModalWhenMutating': False,
                                                             'source': 'project.getActiveSequence',
                                                             'type': 'SequenceProxy | None'},
                                         'encoder': {'canonical': 'encoder',
                                                     'mutatesState': False,
                                                     'raw': False,
                                                     'requiresModalWhenMutating': False,
                                                     'source': 'encoder.getManager',
                                                     'type': 'PremiereEncoder'},
                                         'export': {'canonical': 'export',
                                                    'mutatesState': False,
                                                    'raw': False,
                                                    'requiresModalWhenMutating': False,
                                                    'source': 'export.getExporter',
                                                    'type': 'PremiereExport'},
                                         'project': {'canonical': 'project',
                                                     'mutatesState': False,
                                                     'raw': False,
                                                     'requiresModalWhenMutating': False,
                                                     'source': 'project.getActive',
                                                     'type': 'ProjectProxy | None'},
                                         'sequences': {'canonical': 'sequences',
                                                       'mutatesState': False,
                                                       'raw': False,
                                                       'requiresModalWhenMutating': False,
                                                       'source': 'project.getSequences',
                                                       'type': 'list[SequenceProxy]'},
                                         'version': {'canonical': 'version',
                                                     'mutatesState': False,
                                                     'raw': False,
                                                     'requiresModalWhenMutating': False,
                                                     'source': 'app.getVersion',
                                                     'type': 'str'}}},
             'PremiereApp': {'methods': {},
                             'properties': {'activeProject': {'canonical': 'active_project',
                                                              'mutatesState': False,
                                                              'raw': False,
                                                              'requiresModalWhenMutating': False,
                                                              'source': 'project.getActive',
                                                              'type': 'ProjectProxy | None'},
                                            'activeSequence': {'canonical': 'active_sequence',
                                                               'mutatesState': False,
                                                               'raw': False,
                                                               'requiresModalWhenMutating': False,
                                                               'source': 'project.getActiveSequence',
                                                               'type': 'SequenceProxy | None'},
                                            'active_project': {'canonical': 'active_project',
                                                               'mutatesState': False,
                                                               'raw': False,
                                                               'requiresModalWhenMutating': False,
                                                               'source': 'project.getActive',
                                                               'type': 'ProjectProxy | None'},
                                            'active_sequence': {'canonical': 'active_sequence',
                                                                'mutatesState': False,
                                                                'raw': False,
                                                                'requiresModalWhenMutating': False,
                                                                'source': 'project.getActiveSequence',
                                                                'type': 'SequenceProxy | None'},
                                            'encoder': {'canonical': 'encoder',
                                                        'mutatesState': False,
                                                        'raw': False,
                                                        'requiresModalWhenMutating': False,
                                                        'source': 'encoder.getManager',
                                                        'type': 'PremiereEncoder'},
                                            'export': {'canonical': 'export',
                                                       'mutatesState': False,
                                                       'raw': False,
                                                       'requiresModalWhenMutating': False,
                                                       'source': 'export.getExporter',
                                                       'type': 'PremiereExport'},
                                            'project': {'canonical': 'project',
                                                        'mutatesState': False,
                                                        'raw': False,
                                                        'requiresModalWhenMutating': False,
                                                        'source': 'project.getActive',
                                                        'type': 'ProjectProxy | None'},
                                            'sequences': {'canonical': 'sequences',
                                                          'mutatesState': False,
                                                          'raw': False,
                                                          'requiresModalWhenMutating': False,
                                                          'source': 'project.getSequences',
                                                          'type': 'list[SequenceProxy]'},
                                            'version': {'canonical': 'version',
                                                        'mutatesState': False,
                                                        'raw': False,
                                                        'requiresModalWhenMutating': False,
                                                        'source': 'app.getVersion',
                                                        'type': 'str'}}},
             'PremiereEncoder': {'methods': {'encodeFile': {'canonical': 'encodeFile', 'returns': 'ExportJob'},
                                             'encodeProjectItem': {'canonical': 'encodeProjectItem',
                                                                   'returns': 'ExportJob'},
                                             'encode_file': {'canonical': 'encodeFile', 'returns': 'ExportJob'},
                                             'encode_project_item': {'canonical': 'encodeProjectItem',
                                                                     'returns': 'ExportJob'},
                                             'exportSequence': {'canonical': 'exportSequence', 'returns': 'ExportJob'},
                                             'export_sequence': {'canonical': 'exportSequence', 'returns': 'ExportJob'},
                                             'getExportFileExtension': {'canonical': 'getExportFileExtension',
                                                                        'returns': 'str'},
                                             'getPresets': {'canonical': 'getPresets',
                                                            'returns': 'list[EncoderPreset]'},
                                             'get_export_file_extension': {'canonical': 'getExportFileExtension',
                                                                           'returns': 'str'},
                                             'get_presets': {'canonical': 'getPresets',
                                                             'returns': 'list[EncoderPreset]'}},
                                 'properties': {'isAmeInstalled': {'canonical': 'is_ame_installed',
                                                                   'type': 'bool | None'},
                                                'is_ame_installed': {'canonical': 'is_ame_installed',
                                                                     'type': 'bool | None'},
                                                'presets': {'canonical': 'presets', 'type': 'list[EncoderPreset]'},
                                                'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'PremiereExport': {'methods': {'exportFrame': {'canonical': 'exportFrame', 'returns': 'ExportJob'},
                                            'export_frame': {'canonical': 'exportFrame', 'returns': 'ExportJob'}},
                                'properties': {}},
             'ProjectItemProxy': {'methods': {'createBin': {'canonical': 'createBin', 'returns': 'ProjectItemProxy'},
                                              'create_bin': {'canonical': 'createBin', 'returns': 'ProjectItemProxy'},
                                              'encode': {'canonical': 'encode', 'returns': 'ExportJob'},
                                              'findItemsMatchingMediaPath': {'canonical': 'findItemsMatchingMediaPath',
                                                                             'returns': 'list[ProjectItemProxy]'},
                                              'find_items_matching_media_path': {'canonical': 'findItemsMatchingMediaPath',
                                                                                 'returns': 'list[ProjectItemProxy]'}},
                                  'properties': {'canProxy': {'canonical': 'can_proxy', 'type': 'bool | None'},
                                                 'can_proxy': {'canonical': 'can_proxy', 'type': 'bool | None'},
                                                 'children': {'canonical': 'children',
                                                              'type': 'list[ProjectItemProxy]'},
                                                 'hasProxy': {'canonical': 'has_proxy', 'type': 'bool | None'},
                                                 'has_proxy': {'canonical': 'has_proxy', 'type': 'bool | None'},
                                                 'id': {'canonical': 'id', 'type': 'Any'},
                                                 'isBin': {'canonical': 'is_bin', 'type': 'bool'},
                                                 'isClip': {'canonical': 'is_clip', 'type': 'bool'},
                                                 'isOffline': {'canonical': 'is_offline', 'type': 'bool | None'},
                                                 'isSequence': {'canonical': 'is_sequence', 'type': 'bool'},
                                                 'is_bin': {'canonical': 'is_bin', 'type': 'bool'},
                                                 'is_clip': {'canonical': 'is_clip', 'type': 'bool'},
                                                 'is_offline': {'canonical': 'is_offline', 'type': 'bool | None'},
                                                 'is_sequence': {'canonical': 'is_sequence', 'type': 'bool'},
                                                 'itemType': {'canonical': 'item_type', 'type': 'str | None'},
                                                 'item_type': {'canonical': 'item_type', 'type': 'str | None'},
                                                 'mediaPath': {'canonical': 'media_path', 'type': 'str | None'},
                                                 'media_path': {'canonical': 'media_path', 'type': 'str | None'},
                                                 'name': {'canonical': 'name', 'type': 'str | None'},
                                                 'parentId': {'canonical': 'parent_id', 'type': 'Any'},
                                                 'parent_id': {'canonical': 'parent_id', 'type': 'Any'},
                                                 'path': {'canonical': 'path', 'type': 'str | None'},
                                                 'treePath': {'canonical': 'tree_path', 'type': 'str | None'},
                                                 'tree_path': {'canonical': 'tree_path', 'type': 'str | None'},
                                                 'type': {'canonical': 'type', 'type': 'Any'},
                                                 'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'ProjectProxy': {'methods': {'getSequence': {'canonical': 'getSequence',
                                                          'returns': 'SequenceProxy | None'},
                                          'get_sequence': {'canonical': 'getSequence',
                                                           'returns': 'SequenceProxy | None'},
                                          'importFiles': {'canonical': 'importFiles',
                                                          'returns': 'list[ProjectItemProxy]'},
                                          'import_files': {'canonical': 'importFiles',
                                                           'returns': 'list[ProjectItemProxy]'}},
                              'properties': {'activeSequence': {'canonical': 'active_sequence',
                                                                'type': 'SequenceProxy | None'},
                                             'active_sequence': {'canonical': 'active_sequence',
                                                                 'type': 'SequenceProxy | None'},
                                             'guid': {'canonical': 'guid', 'type': 'str | None'},
                                             'id': {'canonical': 'id', 'type': 'Any'},
                                             'itemCount': {'canonical': 'item_count', 'type': 'int'},
                                             'item_count': {'canonical': 'item_count', 'type': 'int'},
                                             'name': {'canonical': 'name', 'type': 'str | None'},
                                             'path': {'canonical': 'path', 'type': 'str | None'},
                                             'rootItem': {'canonical': 'root_item', 'type': 'ProjectItemProxy | None'},
                                             'root_item': {'canonical': 'root_item', 'type': 'ProjectItemProxy | None'},
                                             'selectedItems': {'canonical': 'selected_items',
                                                               'type': 'list[ProjectItemProxy]'},
                                             'selected_items': {'canonical': 'selected_items',
                                                                'type': 'list[ProjectItemProxy]'},
                                             'sequences': {'canonical': 'sequences', 'type': 'list[SequenceProxy]'}}},
             'SequenceProxy': {'methods': {'createMarker': {'canonical': 'createMarker', 'returns': 'MarkerProxy'},
                                           'create_marker': {'canonical': 'createMarker', 'returns': 'MarkerProxy'},
                                           'export': {'canonical': 'export', 'returns': 'ExportJob'},
                                           'exportFrame': {'canonical': 'exportFrame', 'returns': 'ExportJob'},
                                           'export_frame': {'canonical': 'exportFrame', 'returns': 'ExportJob'}},
                               'properties': {'audioTracks': {'canonical': 'audio_tracks', 'type': 'list[TrackProxy]'},
                                              'audio_tracks': {'canonical': 'audio_tracks', 'type': 'list[TrackProxy]'},
                                              'duration': {'canonical': 'duration', 'type': 'Any'},
                                              'id': {'canonical': 'id', 'type': 'Any'},
                                              'markers': {'canonical': 'markers', 'type': 'list[MarkerProxy]'},
                                              'name': {'canonical': 'name', 'type': 'str | None'},
                                              'selectedClips': {'canonical': 'selected_clips',
                                                                'type': 'list[ClipProxy]'},
                                              'selected_clips': {'canonical': 'selected_clips',
                                                                 'type': 'list[ClipProxy]'},
                                              'sequenceId': {'canonical': 'sequence_id', 'type': 'Any'},
                                              'sequence_id': {'canonical': 'sequence_id', 'type': 'Any'},
                                              'timebase': {'canonical': 'timebase', 'type': 'Any'},
                                              'typename': {'canonical': 'typename', 'type': 'str | None'},
                                              'videoTracks': {'canonical': 'video_tracks', 'type': 'list[TrackProxy]'},
                                              'video_tracks': {'canonical': 'video_tracks',
                                                               'type': 'list[TrackProxy]'}}},
             'TrackProxy': {'methods': {},
                            'properties': {'clips': {'canonical': 'clips', 'type': 'list[ClipProxy]'},
                                           'id': {'canonical': 'id', 'type': 'Any'},
                                           'index': {'canonical': 'index', 'type': 'int | None'},
                                           'isLocked': {'canonical': 'is_locked', 'type': 'bool | None'},
                                           'isMuted': {'canonical': 'is_muted', 'type': 'bool | None'},
                                           'isTargeted': {'canonical': 'is_targeted', 'type': 'bool | None'},
                                           'is_locked': {'canonical': 'is_locked', 'type': 'bool | None'},
                                           'is_muted': {'canonical': 'is_muted', 'type': 'bool | None'},
                                           'is_targeted': {'canonical': 'is_targeted', 'type': 'bool | None'},
                                           'mediaType': {'canonical': 'media_type', 'type': 'str | None'},
                                           'media_type': {'canonical': 'media_type', 'type': 'str | None'},
                                           'name': {'canonical': 'name', 'type': 'str | None'},
                                           'typename': {'canonical': 'typename', 'type': 'str | None'}}}},
 'host': 'premiere',
 'version': '0.1.0'}
