# Generated from generators/ir by generators/ir_to_python.py.
# Do not edit by hand; run `npm run facades:write`.
from __future__ import annotations

FACADE_CONTRACT = {'capabilities': {'bridgeKind': 'generated',
                  'bridgeVersion': '0.1.0',
                  'features': [],
                  'host': 'illustrator',
                  'methods': {'app': ['getVersion'],
                              'artboard': ['getArtboards', 'getActive', 'getActiveIndex'],
                              'compoundPath': ['getCompoundPathItems',
                                               'getSelected',
                                               'getByName',
                                               'getLayerItems',
                                               'getPathItems'],
                              'document': ['getActive'],
                              'export': ['save', 'saveAs', 'exportFile'],
                              'layer': ['getLayers', 'getByName', 'getChildren'],
                              'pageItem': ['getPageItems', 'getSelected', 'getByName', 'getLayerItems'],
                              'pathItem': ['getPathItems', 'getSelected', 'getByName', 'getLayerItems'],
                              'placedItem': ['getPlacedItems', 'getSelected', 'getByName', 'getLayerItems'],
                              'rasterItem': ['getRasterItems', 'getSelected', 'getByName', 'getLayerItems'],
                              'raw': ['evalExtendScript'],
                              'story': ['getStories', 'getByName'],
                              'swatch': ['getSwatches', 'getByName'],
                              'textFrame': ['getTextFrames', 'getSelected', 'getByName', 'setContents']},
                  'namespaces': ['app',
                                 'document',
                                 'artboard',
                                 'layer',
                                 'pageItem',
                                 'pathItem',
                                 'compoundPath',
                                 'placedItem',
                                 'rasterItem',
                                 'textFrame',
                                 'story',
                                 'swatch',
                                 'export',
                                 'raw']},
 'classes': {'ArtboardProxy': {'methods': {},
                               'properties': {'artboardRect': {'canonical': 'artboard_rect', 'type': 'Any'},
                                              'artboard_rect': {'canonical': 'artboard_rect', 'type': 'Any'},
                                              'index': {'canonical': 'index', 'type': 'int | None'},
                                              'name': {'canonical': 'name', 'type': 'str | None'},
                                              'rulerOrigin': {'canonical': 'ruler_origin', 'type': 'Any'},
                                              'rulerPar': {'canonical': 'ruler_par', 'type': 'Any'},
                                              'ruler_origin': {'canonical': 'ruler_origin', 'type': 'Any'},
                                              'ruler_par': {'canonical': 'ruler_par', 'type': 'Any'},
                                              'showCenter': {'canonical': 'show_center', 'type': 'bool | None'},
                                              'showCrossHairs': {'canonical': 'show_cross_hairs',
                                                                 'type': 'bool | None'},
                                              'showSafeAreas': {'canonical': 'show_safe_areas', 'type': 'bool | None'},
                                              'show_center': {'canonical': 'show_center', 'type': 'bool | None'},
                                              'show_cross_hairs': {'canonical': 'show_cross_hairs',
                                                                   'type': 'bool | None'},
                                              'show_safe_areas': {'canonical': 'show_safe_areas',
                                                                  'type': 'bool | None'},
                                              'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'CompoundPathItemProxy': {'methods': {},
                                       'properties': {'controlBounds': {'canonical': 'control_bounds', 'type': 'Any'},
                                                      'control_bounds': {'canonical': 'control_bounds', 'type': 'Any'},
                                                      'editable': {'canonical': 'editable', 'type': 'bool | None'},
                                                      'geometricBounds': {'canonical': 'geometric_bounds',
                                                                          'type': 'Any'},
                                                      'geometric_bounds': {'canonical': 'geometric_bounds',
                                                                           'type': 'Any'},
                                                      'height': {'canonical': 'height', 'type': 'Any'},
                                                      'hidden': {'canonical': 'hidden', 'type': 'bool | None'},
                                                      'id': {'canonical': 'id', 'type': 'Any'},
                                                      'index': {'canonical': 'index', 'type': 'int | None'},
                                                      'itemType': {'canonical': 'item_type', 'type': 'str | None'},
                                                      'item_type': {'canonical': 'item_type', 'type': 'str | None'},
                                                      'layerName': {'canonical': 'layer_name', 'type': 'str | None'},
                                                      'layer_name': {'canonical': 'layer_name', 'type': 'str | None'},
                                                      'locked': {'canonical': 'locked', 'type': 'bool | None'},
                                                      'name': {'canonical': 'name', 'type': 'str | None'},
                                                      'note': {'canonical': 'note', 'type': 'str | None'},
                                                      'opacity': {'canonical': 'opacity', 'type': 'float | None'},
                                                      'parentName': {'canonical': 'parent_name', 'type': 'str | None'},
                                                      'parentTypename': {'canonical': 'parent_typename',
                                                                         'type': 'str | None'},
                                                      'parent_name': {'canonical': 'parent_name', 'type': 'str | None'},
                                                      'parent_typename': {'canonical': 'parent_typename',
                                                                          'type': 'str | None'},
                                                      'pathItemCount': {'canonical': 'path_item_count',
                                                                        'type': 'int | None'},
                                                      'pathItems': {'canonical': 'path_items',
                                                                    'type': 'list[PathItemProxy]'},
                                                      'path_item_count': {'canonical': 'path_item_count',
                                                                          'type': 'int | None'},
                                                      'path_items': {'canonical': 'path_items',
                                                                     'type': 'list[PathItemProxy]'},
                                                      'position': {'canonical': 'position', 'type': 'Any'},
                                                      'selected': {'canonical': 'selected', 'type': 'bool | None'},
                                                      'sliced': {'canonical': 'sliced', 'type': 'bool | None'},
                                                      'typename': {'canonical': 'typename', 'type': 'str | None'},
                                                      'url': {'canonical': 'url', 'type': 'str | None'},
                                                      'visibleBounds': {'canonical': 'visible_bounds', 'type': 'Any'},
                                                      'visible_bounds': {'canonical': 'visible_bounds', 'type': 'Any'},
                                                      'width': {'canonical': 'width', 'type': 'Any'}}},
             'DocumentExportProxy': {'methods': {'file': {'canonical': 'file', 'returns': 'ExportResultProxy'},
                                                 'jpeg': {'canonical': 'jpeg', 'returns': 'ExportResultProxy'},
                                                 'pdf': {'canonical': 'pdf', 'returns': 'ExportResultProxy'},
                                                 'png24': {'canonical': 'png24', 'returns': 'ExportResultProxy'},
                                                 'svg': {'canonical': 'svg', 'returns': 'ExportResultProxy'}},
                                     'properties': {}},
             'DocumentProxy': {'methods': {'exportFile': {'canonical': 'exportFile', 'returns': 'ExportResultProxy'},
                                           'export_file': {'canonical': 'exportFile', 'returns': 'ExportResultProxy'},
                                           'getCompoundPathItemByName': {'canonical': 'getCompoundPathItemByName',
                                                                         'returns': 'CompoundPathItemProxy | None'},
                                           'getLayerByName': {'canonical': 'getLayerByName',
                                                              'returns': 'LayerProxy | None'},
                                           'getPageItemByName': {'canonical': 'getPageItemByName',
                                                                 'returns': 'PageItemProxy | None'},
                                           'getPathItemByName': {'canonical': 'getPathItemByName',
                                                                 'returns': 'PathItemProxy | None'},
                                           'getPlacedItemByName': {'canonical': 'getPlacedItemByName',
                                                                   'returns': 'PlacedItemProxy | None'},
                                           'getRasterItemByName': {'canonical': 'getRasterItemByName',
                                                                   'returns': 'RasterItemProxy | None'},
                                           'getStoryByName': {'canonical': 'getStoryByName',
                                                              'returns': 'StoryProxy | None'},
                                           'getSwatchByName': {'canonical': 'getSwatchByName',
                                                               'returns': 'SwatchProxy | None'},
                                           'getTextFrameByName': {'canonical': 'getTextFrameByName',
                                                                  'returns': 'TextFrameProxy | None'},
                                           'get_compound_path_item_by_name': {'canonical': 'getCompoundPathItemByName',
                                                                              'returns': 'CompoundPathItemProxy | '
                                                                                         'None'},
                                           'get_layer_by_name': {'canonical': 'getLayerByName',
                                                                 'returns': 'LayerProxy | None'},
                                           'get_page_item_by_name': {'canonical': 'getPageItemByName',
                                                                     'returns': 'PageItemProxy | None'},
                                           'get_path_item_by_name': {'canonical': 'getPathItemByName',
                                                                     'returns': 'PathItemProxy | None'},
                                           'get_placed_item_by_name': {'canonical': 'getPlacedItemByName',
                                                                       'returns': 'PlacedItemProxy | None'},
                                           'get_raster_item_by_name': {'canonical': 'getRasterItemByName',
                                                                       'returns': 'RasterItemProxy | None'},
                                           'get_story_by_name': {'canonical': 'getStoryByName',
                                                                 'returns': 'StoryProxy | None'},
                                           'get_swatch_by_name': {'canonical': 'getSwatchByName',
                                                                  'returns': 'SwatchProxy | None'},
                                           'get_text_frame_by_name': {'canonical': 'getTextFrameByName',
                                                                      'returns': 'TextFrameProxy | None'},
                                           'save': {'canonical': 'save', 'returns': 'ExportResultProxy'},
                                           'saveAs': {'canonical': 'saveAs', 'returns': 'ExportResultProxy'},
                                           'save_as': {'canonical': 'saveAs', 'returns': 'ExportResultProxy'}},
                               'properties': {'activeArtboard': {'canonical': 'active_artboard',
                                                                 'type': 'ArtboardProxy | None'},
                                              'activeArtboardIndex': {'canonical': 'active_artboard_index',
                                                                      'type': 'int | None'},
                                              'active_artboard': {'canonical': 'active_artboard',
                                                                  'type': 'ArtboardProxy | None'},
                                              'active_artboard_index': {'canonical': 'active_artboard_index',
                                                                        'type': 'int | None'},
                                              'artboardCount': {'canonical': 'artboard_count', 'type': 'int | None'},
                                              'artboard_count': {'canonical': 'artboard_count', 'type': 'int | None'},
                                              'artboards': {'canonical': 'artboards', 'type': 'list[ArtboardProxy]'},
                                              'compoundPathItemCount': {'canonical': 'compound_path_item_count',
                                                                        'type': 'int | None'},
                                              'compoundPathItems': {'canonical': 'compound_path_items',
                                                                    'type': 'list[CompoundPathItemProxy]'},
                                              'compound_path_item_count': {'canonical': 'compound_path_item_count',
                                                                           'type': 'int | None'},
                                              'compound_path_items': {'canonical': 'compound_path_items',
                                                                      'type': 'list[CompoundPathItemProxy]'},
                                              'exports': {'canonical': 'exports', 'type': 'DocumentExportProxy'},
                                              'height': {'canonical': 'height', 'type': 'Any'},
                                              'layerCount': {'canonical': 'layer_count', 'type': 'int | None'},
                                              'layer_count': {'canonical': 'layer_count', 'type': 'int | None'},
                                              'layers': {'canonical': 'layers', 'type': 'list[LayerProxy]'},
                                              'name': {'canonical': 'name', 'type': 'str | None'},
                                              'pageItemCount': {'canonical': 'page_item_count', 'type': 'int | None'},
                                              'pageItems': {'canonical': 'page_items', 'type': 'list[PageItemProxy]'},
                                              'page_item_count': {'canonical': 'page_item_count', 'type': 'int | None'},
                                              'page_items': {'canonical': 'page_items', 'type': 'list[PageItemProxy]'},
                                              'path': {'canonical': 'path', 'type': 'str | None'},
                                              'pathItemCount': {'canonical': 'path_item_count', 'type': 'int | None'},
                                              'pathItems': {'canonical': 'path_items', 'type': 'list[PathItemProxy]'},
                                              'path_item_count': {'canonical': 'path_item_count', 'type': 'int | None'},
                                              'path_items': {'canonical': 'path_items', 'type': 'list[PathItemProxy]'},
                                              'placedItemCount': {'canonical': 'placed_item_count',
                                                                  'type': 'int | None'},
                                              'placedItems': {'canonical': 'placed_items',
                                                              'type': 'list[PlacedItemProxy]'},
                                              'placed_item_count': {'canonical': 'placed_item_count',
                                                                    'type': 'int | None'},
                                              'placed_items': {'canonical': 'placed_items',
                                                               'type': 'list[PlacedItemProxy]'},
                                              'rasterItemCount': {'canonical': 'raster_item_count',
                                                                  'type': 'int | None'},
                                              'rasterItems': {'canonical': 'raster_items',
                                                              'type': 'list[RasterItemProxy]'},
                                              'raster_item_count': {'canonical': 'raster_item_count',
                                                                    'type': 'int | None'},
                                              'raster_items': {'canonical': 'raster_items',
                                                               'type': 'list[RasterItemProxy]'},
                                              'selectedCompoundPathItems': {'canonical': 'selected_compound_path_items',
                                                                            'type': 'list[CompoundPathItemProxy]'},
                                              'selectedPathItems': {'canonical': 'selected_path_items',
                                                                    'type': 'list[PathItemProxy]'},
                                              'selectedPlacedItems': {'canonical': 'selected_placed_items',
                                                                      'type': 'list[PlacedItemProxy]'},
                                              'selectedRasterItems': {'canonical': 'selected_raster_items',
                                                                      'type': 'list[RasterItemProxy]'},
                                              'selectedTextFrames': {'canonical': 'selected_text_frames',
                                                                     'type': 'list[TextFrameProxy]'},
                                              'selected_compound_path_items': {'canonical': 'selected_compound_path_items',
                                                                               'type': 'list[CompoundPathItemProxy]'},
                                              'selected_path_items': {'canonical': 'selected_path_items',
                                                                      'type': 'list[PathItemProxy]'},
                                              'selected_placed_items': {'canonical': 'selected_placed_items',
                                                                        'type': 'list[PlacedItemProxy]'},
                                              'selected_raster_items': {'canonical': 'selected_raster_items',
                                                                        'type': 'list[RasterItemProxy]'},
                                              'selected_text_frames': {'canonical': 'selected_text_frames',
                                                                       'type': 'list[TextFrameProxy]'},
                                              'selection': {'canonical': 'selection', 'type': 'list[PageItemProxy]'},
                                              'selectionCount': {'canonical': 'selection_count', 'type': 'int | None'},
                                              'selection_count': {'canonical': 'selection_count', 'type': 'int | None'},
                                              'stories': {'canonical': 'stories', 'type': 'list[StoryProxy]'},
                                              'storyCount': {'canonical': 'story_count', 'type': 'int | None'},
                                              'story_count': {'canonical': 'story_count', 'type': 'int | None'},
                                              'swatchCount': {'canonical': 'swatch_count', 'type': 'int | None'},
                                              'swatch_count': {'canonical': 'swatch_count', 'type': 'int | None'},
                                              'swatches': {'canonical': 'swatches', 'type': 'list[SwatchProxy]'},
                                              'textFrameCount': {'canonical': 'text_frame_count', 'type': 'int | None'},
                                              'textFrames': {'canonical': 'text_frames',
                                                             'type': 'list[TextFrameProxy]'},
                                              'text_frame_count': {'canonical': 'text_frame_count',
                                                                   'type': 'int | None'},
                                              'text_frames': {'canonical': 'text_frames',
                                                              'type': 'list[TextFrameProxy]'},
                                              'typename': {'canonical': 'typename', 'type': 'str | None'},
                                              'width': {'canonical': 'width', 'type': 'Any'}}},
             'ExportResultProxy': {'methods': {},
                                   'properties': {'documentName': {'canonical': 'document_name', 'type': 'str | None'},
                                                  'document_name': {'canonical': 'document_name', 'type': 'str | None'},
                                                  'format': {'canonical': 'format', 'type': 'str | None'},
                                                  'ok': {'canonical': 'ok', 'type': 'bool | None'},
                                                  'options': {'canonical': 'options', 'type': 'dict[str, Any]'},
                                                  'path': {'canonical': 'path', 'type': 'str | None'},
                                                  'preset': {'canonical': 'preset', 'type': 'str | None'},
                                                  'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'Illustrator': {'methods': {},
                             'properties': {'activeDocument': {'canonical': 'active_document',
                                                               'mutatesState': False,
                                                               'raw': False,
                                                               'requiresModalWhenMutating': False,
                                                               'source': 'document.getActive',
                                                               'type': 'DocumentProxy | None'},
                                            'active_document': {'canonical': 'active_document',
                                                                'mutatesState': False,
                                                                'raw': False,
                                                                'requiresModalWhenMutating': False,
                                                                'source': 'document.getActive',
                                                                'type': 'DocumentProxy | None'},
                                            'version': {'canonical': 'version',
                                                        'mutatesState': False,
                                                        'raw': False,
                                                        'requiresModalWhenMutating': False,
                                                        'source': 'app.getVersion',
                                                        'type': 'str'}}},
             'IllustratorApp': {'methods': {},
                                'properties': {'activeDocument': {'canonical': 'active_document',
                                                                  'mutatesState': False,
                                                                  'raw': False,
                                                                  'requiresModalWhenMutating': False,
                                                                  'source': 'document.getActive',
                                                                  'type': 'DocumentProxy | None'},
                                               'active_document': {'canonical': 'active_document',
                                                                   'mutatesState': False,
                                                                   'raw': False,
                                                                   'requiresModalWhenMutating': False,
                                                                   'source': 'document.getActive',
                                                                   'type': 'DocumentProxy | None'},
                                               'version': {'canonical': 'version',
                                                           'mutatesState': False,
                                                           'raw': False,
                                                           'requiresModalWhenMutating': False,
                                                           'source': 'app.getVersion',
                                                           'type': 'str'}}},
             'LayerProxy': {'methods': {},
                            'properties': {'compoundPathItems': {'canonical': 'compound_path_items',
                                                                 'type': 'list[CompoundPathItemProxy]'},
                                           'compound_path_items': {'canonical': 'compound_path_items',
                                                                   'type': 'list[CompoundPathItemProxy]'},
                                           'hasSelectedArtwork': {'canonical': 'has_selected_artwork',
                                                                  'type': 'bool | None'},
                                           'has_selected_artwork': {'canonical': 'has_selected_artwork',
                                                                    'type': 'bool | None'},
                                           'id': {'canonical': 'id', 'type': 'Any'},
                                           'index': {'canonical': 'index', 'type': 'int | None'},
                                           'layerCount': {'canonical': 'layer_count', 'type': 'int | None'},
                                           'layer_count': {'canonical': 'layer_count', 'type': 'int | None'},
                                           'layers': {'canonical': 'layers', 'type': 'list[LayerProxy]'},
                                           'locked': {'canonical': 'locked', 'type': 'bool | None'},
                                           'name': {'canonical': 'name', 'type': 'str | None'},
                                           'opacity': {'canonical': 'opacity', 'type': 'float | None'},
                                           'pageItemCount': {'canonical': 'page_item_count', 'type': 'int | None'},
                                           'pageItems': {'canonical': 'page_items', 'type': 'list[PageItemProxy]'},
                                           'page_item_count': {'canonical': 'page_item_count', 'type': 'int | None'},
                                           'page_items': {'canonical': 'page_items', 'type': 'list[PageItemProxy]'},
                                           'parentName': {'canonical': 'parent_name', 'type': 'str | None'},
                                           'parentTypename': {'canonical': 'parent_typename', 'type': 'str | None'},
                                           'parent_name': {'canonical': 'parent_name', 'type': 'str | None'},
                                           'parent_typename': {'canonical': 'parent_typename', 'type': 'str | None'},
                                           'pathItems': {'canonical': 'path_items', 'type': 'list[PathItemProxy]'},
                                           'path_items': {'canonical': 'path_items', 'type': 'list[PathItemProxy]'},
                                           'placedItems': {'canonical': 'placed_items',
                                                           'type': 'list[PlacedItemProxy]'},
                                           'placed_items': {'canonical': 'placed_items',
                                                            'type': 'list[PlacedItemProxy]'},
                                           'preview': {'canonical': 'preview', 'type': 'bool | None'},
                                           'printable': {'canonical': 'printable', 'type': 'bool | None'},
                                           'rasterItems': {'canonical': 'raster_items',
                                                           'type': 'list[RasterItemProxy]'},
                                           'raster_items': {'canonical': 'raster_items',
                                                            'type': 'list[RasterItemProxy]'},
                                           'typename': {'canonical': 'typename', 'type': 'str | None'},
                                           'visible': {'canonical': 'visible', 'type': 'bool | None'}}},
             'PageItemProxy': {'methods': {},
                               'properties': {'controlBounds': {'canonical': 'control_bounds', 'type': 'Any'},
                                              'control_bounds': {'canonical': 'control_bounds', 'type': 'Any'},
                                              'editable': {'canonical': 'editable', 'type': 'bool | None'},
                                              'geometricBounds': {'canonical': 'geometric_bounds', 'type': 'Any'},
                                              'geometric_bounds': {'canonical': 'geometric_bounds', 'type': 'Any'},
                                              'height': {'canonical': 'height', 'type': 'Any'},
                                              'hidden': {'canonical': 'hidden', 'type': 'bool | None'},
                                              'id': {'canonical': 'id', 'type': 'Any'},
                                              'index': {'canonical': 'index', 'type': 'int | None'},
                                              'itemType': {'canonical': 'item_type', 'type': 'str | None'},
                                              'item_type': {'canonical': 'item_type', 'type': 'str | None'},
                                              'layerName': {'canonical': 'layer_name', 'type': 'str | None'},
                                              'layer_name': {'canonical': 'layer_name', 'type': 'str | None'},
                                              'locked': {'canonical': 'locked', 'type': 'bool | None'},
                                              'name': {'canonical': 'name', 'type': 'str | None'},
                                              'note': {'canonical': 'note', 'type': 'str | None'},
                                              'opacity': {'canonical': 'opacity', 'type': 'float | None'},
                                              'parentName': {'canonical': 'parent_name', 'type': 'str | None'},
                                              'parentTypename': {'canonical': 'parent_typename', 'type': 'str | None'},
                                              'parent_name': {'canonical': 'parent_name', 'type': 'str | None'},
                                              'parent_typename': {'canonical': 'parent_typename', 'type': 'str | None'},
                                              'position': {'canonical': 'position', 'type': 'Any'},
                                              'selected': {'canonical': 'selected', 'type': 'bool | None'},
                                              'sliced': {'canonical': 'sliced', 'type': 'bool | None'},
                                              'typename': {'canonical': 'typename', 'type': 'str | None'},
                                              'url': {'canonical': 'url', 'type': 'str | None'},
                                              'visibleBounds': {'canonical': 'visible_bounds', 'type': 'Any'},
                                              'visible_bounds': {'canonical': 'visible_bounds', 'type': 'Any'},
                                              'width': {'canonical': 'width', 'type': 'Any'}}},
             'PathItemProxy': {'methods': {'resize': {'canonical': 'resize', 'returns': 'Any'},
                                           'rotate': {'canonical': 'rotate', 'returns': 'Any'},
                                           'setEntirePath': {'canonical': 'setEntirePath', 'returns': 'Any'},
                                           'set_entire_path': {'canonical': 'setEntirePath', 'returns': 'Any'},
                                           'translate': {'canonical': 'translate', 'returns': 'Any'}},
                               'properties': {'area': {'canonical': 'area', 'type': 'float | None'},
                                              'clipping': {'canonical': 'clipping', 'type': 'bool | None'},
                                              'closed': {'canonical': 'closed', 'type': 'bool | None'},
                                              'controlBounds': {'canonical': 'control_bounds', 'type': 'Any'},
                                              'control_bounds': {'canonical': 'control_bounds', 'type': 'Any'},
                                              'editable': {'canonical': 'editable', 'type': 'bool | None'},
                                              'evenodd': {'canonical': 'evenodd', 'type': 'bool | None'},
                                              'fillColor': {'canonical': 'fill_color', 'type': 'Any'},
                                              'fillOverprint': {'canonical': 'fill_overprint', 'type': 'bool | None'},
                                              'fill_color': {'canonical': 'fill_color', 'type': 'Any'},
                                              'fill_overprint': {'canonical': 'fill_overprint', 'type': 'bool | None'},
                                              'filled': {'canonical': 'filled', 'type': 'bool | None'},
                                              'geometricBounds': {'canonical': 'geometric_bounds', 'type': 'Any'},
                                              'geometric_bounds': {'canonical': 'geometric_bounds', 'type': 'Any'},
                                              'guides': {'canonical': 'guides', 'type': 'bool | None'},
                                              'height': {'canonical': 'height', 'type': 'Any'},
                                              'hidden': {'canonical': 'hidden', 'type': 'bool | None'},
                                              'id': {'canonical': 'id', 'type': 'Any'},
                                              'index': {'canonical': 'index', 'type': 'int | None'},
                                              'itemType': {'canonical': 'item_type', 'type': 'str | None'},
                                              'item_type': {'canonical': 'item_type', 'type': 'str | None'},
                                              'layerName': {'canonical': 'layer_name', 'type': 'str | None'},
                                              'layer_name': {'canonical': 'layer_name', 'type': 'str | None'},
                                              'length': {'canonical': 'length', 'type': 'float | None'},
                                              'locked': {'canonical': 'locked', 'type': 'bool | None'},
                                              'name': {'canonical': 'name', 'type': 'str | None'},
                                              'note': {'canonical': 'note', 'type': 'str | None'},
                                              'opacity': {'canonical': 'opacity', 'type': 'float | None'},
                                              'parentName': {'canonical': 'parent_name', 'type': 'str | None'},
                                              'parentTypename': {'canonical': 'parent_typename', 'type': 'str | None'},
                                              'parent_name': {'canonical': 'parent_name', 'type': 'str | None'},
                                              'parent_typename': {'canonical': 'parent_typename', 'type': 'str | None'},
                                              'pathPointCount': {'canonical': 'path_point_count', 'type': 'int | None'},
                                              'path_point_count': {'canonical': 'path_point_count',
                                                                   'type': 'int | None'},
                                              'pixelAligned': {'canonical': 'pixel_aligned', 'type': 'bool | None'},
                                              'pixel_aligned': {'canonical': 'pixel_aligned', 'type': 'bool | None'},
                                              'polarity': {'canonical': 'polarity', 'type': 'Any'},
                                              'position': {'canonical': 'position', 'type': 'Any'},
                                              'selected': {'canonical': 'selected', 'type': 'bool | None'},
                                              'selectedPathPointCount': {'canonical': 'selected_path_point_count',
                                                                         'type': 'int | None'},
                                              'selected_path_point_count': {'canonical': 'selected_path_point_count',
                                                                            'type': 'int | None'},
                                              'sliced': {'canonical': 'sliced', 'type': 'bool | None'},
                                              'strokeCap': {'canonical': 'stroke_cap', 'type': 'Any'},
                                              'strokeColor': {'canonical': 'stroke_color', 'type': 'Any'},
                                              'strokeDashOffset': {'canonical': 'stroke_dash_offset',
                                                                   'type': 'float | None'},
                                              'strokeDashes': {'canonical': 'stroke_dashes', 'type': 'Any'},
                                              'strokeJoin': {'canonical': 'stroke_join', 'type': 'Any'},
                                              'strokeMiterLimit': {'canonical': 'stroke_miter_limit',
                                                                   'type': 'float | None'},
                                              'strokeOverprint': {'canonical': 'stroke_overprint',
                                                                  'type': 'bool | None'},
                                              'strokeWidth': {'canonical': 'stroke_width', 'type': 'float | None'},
                                              'stroke_cap': {'canonical': 'stroke_cap', 'type': 'Any'},
                                              'stroke_color': {'canonical': 'stroke_color', 'type': 'Any'},
                                              'stroke_dash_offset': {'canonical': 'stroke_dash_offset',
                                                                     'type': 'float | None'},
                                              'stroke_dashes': {'canonical': 'stroke_dashes', 'type': 'Any'},
                                              'stroke_join': {'canonical': 'stroke_join', 'type': 'Any'},
                                              'stroke_miter_limit': {'canonical': 'stroke_miter_limit',
                                                                     'type': 'float | None'},
                                              'stroke_overprint': {'canonical': 'stroke_overprint',
                                                                   'type': 'bool | None'},
                                              'stroke_width': {'canonical': 'stroke_width', 'type': 'float | None'},
                                              'stroked': {'canonical': 'stroked', 'type': 'bool | None'},
                                              'typename': {'canonical': 'typename', 'type': 'str | None'},
                                              'url': {'canonical': 'url', 'type': 'str | None'},
                                              'visibleBounds': {'canonical': 'visible_bounds', 'type': 'Any'},
                                              'visible_bounds': {'canonical': 'visible_bounds', 'type': 'Any'},
                                              'width': {'canonical': 'width', 'type': 'Any'}}},
             'PlacedItemProxy': {'methods': {},
                                 'properties': {'boundingBox': {'canonical': 'bounding_box', 'type': 'Any'},
                                                'bounding_box': {'canonical': 'bounding_box', 'type': 'Any'},
                                                'controlBounds': {'canonical': 'control_bounds', 'type': 'Any'},
                                                'control_bounds': {'canonical': 'control_bounds', 'type': 'Any'},
                                                'editable': {'canonical': 'editable', 'type': 'bool | None'},
                                                'fileName': {'canonical': 'file_name', 'type': 'str | None'},
                                                'filePath': {'canonical': 'file_path', 'type': 'str | None'},
                                                'file_name': {'canonical': 'file_name', 'type': 'str | None'},
                                                'file_path': {'canonical': 'file_path', 'type': 'str | None'},
                                                'geometricBounds': {'canonical': 'geometric_bounds', 'type': 'Any'},
                                                'geometric_bounds': {'canonical': 'geometric_bounds', 'type': 'Any'},
                                                'height': {'canonical': 'height', 'type': 'Any'},
                                                'hidden': {'canonical': 'hidden', 'type': 'bool | None'},
                                                'id': {'canonical': 'id', 'type': 'Any'},
                                                'index': {'canonical': 'index', 'type': 'int | None'},
                                                'itemType': {'canonical': 'item_type', 'type': 'str | None'},
                                                'item_type': {'canonical': 'item_type', 'type': 'str | None'},
                                                'layerName': {'canonical': 'layer_name', 'type': 'str | None'},
                                                'layer_name': {'canonical': 'layer_name', 'type': 'str | None'},
                                                'locked': {'canonical': 'locked', 'type': 'bool | None'},
                                                'matrix': {'canonical': 'matrix', 'type': 'Any'},
                                                'name': {'canonical': 'name', 'type': 'str | None'},
                                                'note': {'canonical': 'note', 'type': 'str | None'},
                                                'opacity': {'canonical': 'opacity', 'type': 'float | None'},
                                                'parentName': {'canonical': 'parent_name', 'type': 'str | None'},
                                                'parentTypename': {'canonical': 'parent_typename',
                                                                   'type': 'str | None'},
                                                'parent_name': {'canonical': 'parent_name', 'type': 'str | None'},
                                                'parent_typename': {'canonical': 'parent_typename',
                                                                    'type': 'str | None'},
                                                'position': {'canonical': 'position', 'type': 'Any'},
                                                'selected': {'canonical': 'selected', 'type': 'bool | None'},
                                                'sliced': {'canonical': 'sliced', 'type': 'bool | None'},
                                                'typename': {'canonical': 'typename', 'type': 'str | None'},
                                                'url': {'canonical': 'url', 'type': 'str | None'},
                                                'visibleBounds': {'canonical': 'visible_bounds', 'type': 'Any'},
                                                'visible_bounds': {'canonical': 'visible_bounds', 'type': 'Any'},
                                                'width': {'canonical': 'width', 'type': 'Any'}}},
             'RasterItemProxy': {'methods': {},
                                 'properties': {'bitsPerChannel': {'canonical': 'bits_per_channel',
                                                                   'type': 'int | None'},
                                                'bits_per_channel': {'canonical': 'bits_per_channel',
                                                                     'type': 'int | None'},
                                                'boundingBox': {'canonical': 'bounding_box', 'type': 'Any'},
                                                'bounding_box': {'canonical': 'bounding_box', 'type': 'Any'},
                                                'channels': {'canonical': 'channels', 'type': 'int | None'},
                                                'colorants': {'canonical': 'colorants', 'type': 'Any'},
                                                'colorizedGrayscale': {'canonical': 'colorized_grayscale',
                                                                       'type': 'bool | None'},
                                                'colorized_grayscale': {'canonical': 'colorized_grayscale',
                                                                        'type': 'bool | None'},
                                                'controlBounds': {'canonical': 'control_bounds', 'type': 'Any'},
                                                'control_bounds': {'canonical': 'control_bounds', 'type': 'Any'},
                                                'editable': {'canonical': 'editable', 'type': 'bool | None'},
                                                'embedded': {'canonical': 'embedded', 'type': 'bool | None'},
                                                'fileName': {'canonical': 'file_name', 'type': 'str | None'},
                                                'filePath': {'canonical': 'file_path', 'type': 'str | None'},
                                                'file_name': {'canonical': 'file_name', 'type': 'str | None'},
                                                'file_path': {'canonical': 'file_path', 'type': 'str | None'},
                                                'geometricBounds': {'canonical': 'geometric_bounds', 'type': 'Any'},
                                                'geometric_bounds': {'canonical': 'geometric_bounds', 'type': 'Any'},
                                                'height': {'canonical': 'height', 'type': 'Any'},
                                                'hidden': {'canonical': 'hidden', 'type': 'bool | None'},
                                                'id': {'canonical': 'id', 'type': 'Any'},
                                                'imageColorSpace': {'canonical': 'image_color_space', 'type': 'Any'},
                                                'image_color_space': {'canonical': 'image_color_space', 'type': 'Any'},
                                                'index': {'canonical': 'index', 'type': 'int | None'},
                                                'itemType': {'canonical': 'item_type', 'type': 'str | None'},
                                                'item_type': {'canonical': 'item_type', 'type': 'str | None'},
                                                'layerName': {'canonical': 'layer_name', 'type': 'str | None'},
                                                'layer_name': {'canonical': 'layer_name', 'type': 'str | None'},
                                                'locked': {'canonical': 'locked', 'type': 'bool | None'},
                                                'matrix': {'canonical': 'matrix', 'type': 'Any'},
                                                'name': {'canonical': 'name', 'type': 'str | None'},
                                                'note': {'canonical': 'note', 'type': 'str | None'},
                                                'opacity': {'canonical': 'opacity', 'type': 'float | None'},
                                                'overprint': {'canonical': 'overprint', 'type': 'bool | None'},
                                                'parentName': {'canonical': 'parent_name', 'type': 'str | None'},
                                                'parentTypename': {'canonical': 'parent_typename',
                                                                   'type': 'str | None'},
                                                'parent_name': {'canonical': 'parent_name', 'type': 'str | None'},
                                                'parent_typename': {'canonical': 'parent_typename',
                                                                    'type': 'str | None'},
                                                'position': {'canonical': 'position', 'type': 'Any'},
                                                'selected': {'canonical': 'selected', 'type': 'bool | None'},
                                                'sliced': {'canonical': 'sliced', 'type': 'bool | None'},
                                                'typename': {'canonical': 'typename', 'type': 'str | None'},
                                                'url': {'canonical': 'url', 'type': 'str | None'},
                                                'visibleBounds': {'canonical': 'visible_bounds', 'type': 'Any'},
                                                'visible_bounds': {'canonical': 'visible_bounds', 'type': 'Any'},
                                                'width': {'canonical': 'width', 'type': 'Any'}}},
             'StoryProxy': {'methods': {},
                            'properties': {'contents': {'canonical': 'contents', 'type': 'str | None'},
                                           'id': {'canonical': 'id', 'type': 'Any'},
                                           'index': {'canonical': 'index', 'type': 'int | None'},
                                           'length': {'canonical': 'length', 'type': 'int | None'},
                                           'name': {'canonical': 'name', 'type': 'str | None'},
                                           'paragraphCount': {'canonical': 'paragraph_count', 'type': 'int | None'},
                                           'paragraph_count': {'canonical': 'paragraph_count', 'type': 'int | None'},
                                           'textFrameCount': {'canonical': 'text_frame_count', 'type': 'int | None'},
                                           'text_frame_count': {'canonical': 'text_frame_count', 'type': 'int | None'},
                                           'typename': {'canonical': 'typename', 'type': 'str | None'},
                                           'wordCount': {'canonical': 'word_count', 'type': 'int | None'},
                                           'word_count': {'canonical': 'word_count', 'type': 'int | None'}}},
             'SwatchProxy': {'methods': {},
                             'properties': {'color': {'canonical': 'color', 'type': 'Any'},
                                            'colorTypename': {'canonical': 'color_typename', 'type': 'str | None'},
                                            'color_typename': {'canonical': 'color_typename', 'type': 'str | None'},
                                            'index': {'canonical': 'index', 'type': 'int | None'},
                                            'name': {'canonical': 'name', 'type': 'str | None'},
                                            'typename': {'canonical': 'typename', 'type': 'str | None'}}},
             'TextFrameProxy': {'methods': {'setContents': {'canonical': 'setContents', 'returns': 'TextFrameProxy'},
                                            'set_contents': {'canonical': 'setContents', 'returns': 'TextFrameProxy'}},
                                'properties': {'characterCount': {'canonical': 'character_count', 'type': 'int | None'},
                                               'character_count': {'canonical': 'character_count',
                                                                   'type': 'int | None'},
                                               'contents': {'canonical': 'contents', 'type': 'str | None'},
                                               'geometricBounds': {'canonical': 'geometric_bounds', 'type': 'Any'},
                                               'geometric_bounds': {'canonical': 'geometric_bounds', 'type': 'Any'},
                                               'height': {'canonical': 'height', 'type': 'Any'},
                                               'id': {'canonical': 'id', 'type': 'Any'},
                                               'index': {'canonical': 'index', 'type': 'int | None'},
                                               'kind': {'canonical': 'kind', 'type': 'Any'},
                                               'layerName': {'canonical': 'layer_name', 'type': 'str | None'},
                                               'layer_name': {'canonical': 'layer_name', 'type': 'str | None'},
                                               'name': {'canonical': 'name', 'type': 'str | None'},
                                               'orientation': {'canonical': 'orientation', 'type': 'Any'},
                                               'paragraphCount': {'canonical': 'paragraph_count', 'type': 'int | None'},
                                               'paragraph_count': {'canonical': 'paragraph_count',
                                                                   'type': 'int | None'},
                                               'position': {'canonical': 'position', 'type': 'Any'},
                                               'selected': {'canonical': 'selected', 'type': 'bool | None'},
                                               'typename': {'canonical': 'typename', 'type': 'str | None'},
                                               'visibleBounds': {'canonical': 'visible_bounds', 'type': 'Any'},
                                               'visible_bounds': {'canonical': 'visible_bounds', 'type': 'Any'},
                                               'width': {'canonical': 'width', 'type': 'Any'},
                                               'wordCount': {'canonical': 'word_count', 'type': 'int | None'},
                                               'word_count': {'canonical': 'word_count', 'type': 'int | None'}}}},
 'host': 'illustrator',
 'version': '0.1.0'}
